## Imports

In [2]:
import logging
import os
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd
import googlemaps
from google.oauth2 import service_account
from googleapiclient.discovery import build
import numpy as np

## Set up Logging

In [3]:
# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('scrape_google_maps_reviews.log', mode='w'),  # Log to file
        logging.StreamHandler(sys.stdout)  # Log to console (for Jupyter/real-time output)
    ]
)

## Read Addresses from Google Sheet

In [4]:
# Load credentials from the JSON key file
SERVICE_ACCOUNT_FILE = '/Users/madhumithakumar/Documents/bgorg_clients/google_sheets_service_account_key.json'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']

credentials = service_account.Credentials.from_service_account_file(
    SERVICE_ACCOUNT_FILE, scopes=SCOPES
)

# Google Sheets ID and Range
SPREADSHEET_ID = '11-bAMl8nkpcQK1uxoRZ2pCZ1AKm70Wuu56McK0Uk5PU'
RANGE_NAME = 'Naturals!A1:G200'  # Adjust as needed

# Load Google Sheets data into a DataFrame
def fetch_data_from_gsheet():
    try:
        # Build the Google Sheets API service
        service = build('sheets', 'v4', credentials=credentials)
        sheet = service.spreadsheets()

        # Fetch data from the specified range
        result = sheet.values().get(spreadsheetId=SPREADSHEET_ID, range=RANGE_NAME).execute()
        values = result.get('values', [])

        # Convert the fetched data to a DataFrame
        if values:
            df = pd.DataFrame(values[1:], columns=values[0])  # First row as header
        else:
            df = pd.DataFrame()

        return df

    except Exception as e:
        print(f"Error fetching data: {e}")
        return None

In [5]:
df = fetch_data_from_gsheet()

2025-01-15 16:08:50,421 - INFO - file_cache is only supported with oauth2client<4.0.0

In [6]:
df.head()

,City,Area,Address,Business Name,Status,Franchise Owner,Subscription
0,Chennai,Alwarpet,"No 220, Mowbrays Flats, TT Krishnamachari Road...",,NA,None,None
1,Chennai,Alwarpet,"No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...","Naturals Salon & Spa CP Ramaswamy road , Alwar...",NA,None,None
2,Chennai,"Adambakkam, Brindavan Nagar","N37 First Flr, 2nd Street Shawalace Col, Brind...",Naturals Salon,NA,None,None
3,Chennai,"Adambakkam,Secretariat Colony rd","No 16A/17, Secretariat Col, City Link Rd, Adam...",,NA,None,None
4,Chennai,Adyar,"No 31, Ground Floor, Ceebros Enclave, 1st Main...",,NA,None,None

In [7]:
len(df)

148

## Places API

In [14]:
api_key = "AIzaSyB-wyVE7zyFMPwRKDQmw5fLrTluF_nAAxQ"

In [8]:
# def scrape_google_maps_reviews(api_key, business_name, city_name, max_locations):
#     """
#     Extract metadata for up to 200 locations using pagination in the Google Places API.
#     Extract all reviews into a single CSV file and save Google Maps URLs to a text file.

#     Parameters:
#         api_key (str): Google API key.
#         business_name (str): Business name to query.
#         city_name (str): City name for the search.
#         max_locations (int): Total number of locations to extract.

#     Returns:
#         None: Saves the data to CSV files and URLs to a text file.
#     """
#     logging.info("Starting the scrape_google_maps_reviews function")
#     gmaps = googlemaps.Client(key=api_key)
#     location_data = []
#     all_reviews = []
#     urls = []  # To store the URLs

#     try:
#         processed_locations = 0
#         next_page_token = None

#         while processed_locations < max_locations:
#             # Fetch places using the API
#             query = f"{business_name}, {city_name}"
#             if next_page_token:
#                 response = gmaps.places(query=query, page_token=next_page_token)
#             else:
#                 response = gmaps.places(query=query)

#             # Handle API errors
#             if response.get("status") != "OK":
#                 logging.error(f"Places API failed: {response.get('status')}")
#                 break

#             # Process results
#             results = response.get("results", [])
#             for place in results:
#                 if processed_locations >= max_locations:
#                     break

#                 place_id = place["place_id"]
#                 name = place.get("name", "N/A")
#                 address = place.get("formatted_address", "N/A")
#                 rating = place.get("rating", "N/A")
#                 location_id = f"LOC_{processed_locations + 1}"
#                 user_ratings_total = place.get("user_ratings_total", 0)

#                 # Generate Google Maps URL
#                 url = f"https://www.google.com/maps/place/?q=place_id:{place_id}"
#                 urls.append(url)  # Add URL to list

#                 location_data.append({
#                     "Location ID": location_id,
#                     "City Area": city_name,
#                     "Name": name,
#                     "Address": address,
#                     "Rating": rating,
#                     "Total Reviews": user_ratings_total,
#                     "Place ID": place_id,
#                     "Google Maps URL": url
#                 })

#                 # Fetch reviews for the current location
#                 try:
#                     place_details = gmaps.place(place_id=place_id, fields=["reviews"])
#                     reviews = place_details.get("result", {}).get("reviews", [])

#                     for review in reviews:
#                         reviewer_name = review.get("author_name", "N/A")
#                         review_text = review.get("text", "No text")
#                         review_rating = review.get("rating", "N/A")
#                         review_timestamp = review.get("time")
#                         review_date_actual = datetime.utcfromtimestamp(review_timestamp).strftime('%Y-%m-%d %H:%M:%S') if review_timestamp else "N/A"

#                         all_reviews.append({
#                             "Location ID": location_id,
#                             "City Area": city_name,
#                             "Business Name": name,
#                             "Address": address,
#                             "Reviewer Name": reviewer_name,
#                             "Review": review_text,
#                             "Rating": review_rating,
#                             "Review Date": review_date_actual,
#                             "Place ID": place_id
#                         })

#                 except Exception as e:
#                     logging.warning(f"Failed to fetch reviews for {name}: {e}")

#                 processed_locations += 1

#             # Check for pagination token
#             next_page_token = response.get("next_page_token")
#             if not next_page_token:
#                 logging.info("No more pages available.")
#                 break

#             logging.info("Waiting for next page token to activate...")
#             time.sleep(3)  # Wait for the token to become active

#         # Save location data to CSV
#         pd.DataFrame(location_data).to_csv(f"data/location_data/naturals_{city_name}_data.csv", index=False)
#         logging.info(f"Successfully saved {processed_locations} locations to f'data/{business_name}_{city_name}_data.csv'.")

#         # Save all reviews to a single CSV
#         if all_reviews:
#             pd.DataFrame(all_reviews).to_csv(f"data/review_data/naturals_{city_name}_reviews.csv", index=False)
#             logging.info(f"Successfully saved all reviews to f'data/{business_name}_{city_name}_all_reviews.csv'.")
#         else:
#             logging.warning("No reviews were found for any location.")

#         # Save Google Maps URLs to a text file
#         with open(f"data/location_data/maps_urls/{city_name}.txt", "w") as file:
#             for url in urls:
#                 file.write(url + "\n")
#         logging.info(f"Successfully saved Google Maps URLs to 'data/location_data/maps_urls/{city_name}.txt'.")

#     except Exception as e:
#         logging.error(f"An error occurred: {e}")

In [9]:
# scrape_google_maps_reviews(api_key, "Naturals Signature", "Chennai South", 100)

## Go from Google Sheet
Pass address directly

In [10]:
api_key = "AIzaSyB-wyVE7zyFMPwRKDQmw5fLrTluF_nAAxQ"

In [11]:
# def scrape_google_maps_metadata(api_key, business_name, city_name, max_locations):
#     """
#     Extract metadata for up to `max_locations` using pagination in the Google Places API.

#     Parameters:
#         api_key (str): Google API key.
#         business_name (str): Business name to query.
#         city_name (str): City name for the search.
#         max_locations (int): Total number of locations to extract.

#     Returns:
#         list[dict]: List of metadata dictionaries for the locations.
#     """
#     import googlemaps
#     import logging
#     import time

#     logging.info("Starting the scrape_google_maps_metadata function")
#     gmaps = googlemaps.Client(key=api_key)
#     location_data = []

#     try:
#         processed_locations = 0
#         next_page_token = None

#         while processed_locations < max_locations:
#             # Fetch places using the API
#             query = f"{business_name}, {city_name}"
#             if next_page_token:
#                 response = gmaps.places(query=query, page_token=next_page_token)
#             else:
#                 response = gmaps.places(query=query)

#             # Handle API errors
#             if response.get("status") != "OK":
#                 logging.error(f"Places API failed: {response.get('status')}")
#                 break

#             # Process results
#             results = response.get("results", [])
#             for place in results:
#                 if processed_locations >= max_locations:
#                     break

#                 place_id = place["place_id"]
#                 name = place.get("name", "N/A")
#                 address = place.get("formatted_address", "N/A")
#                 rating = place.get("rating", "N/A")
#                 user_ratings_total = place.get("user_ratings_total", 0)

#                 # Generate Google Maps URL
#                 url = f"https://www.google.com/maps/place/?q=place_id:{place_id}"

#                 location_data.append({
#                     "Location ID": f"LOC_{processed_locations + 1}",
#                     "City Area": city_name,
#                     "Name": name,
#                     "Address": address,
#                     "Rating": rating,
#                     "Total Reviews": user_ratings_total,
#                     "Place ID": place_id,
#                     "Google Maps URL": url
#                 })

#                 processed_locations += 1

#             # Check for pagination token
#             next_page_token = response.get("next_page_token")
#             if not next_page_token:
#                 logging.info("No more pages available.")
#                 break

#             logging.info("Waiting for next page token to activate...")
#             time.sleep(3)  # Wait for the token to become active

#     except Exception as e:
#         logging.error(f"An error occurred: {e}")

#     return location_data

In [22]:
def scrape_google_maps_metadata(api_key, business_name, city_name, area_name, max_locations):
    """
    Extract metadata for up to `max_locations` using pagination in the Google Places API,
    including latitude and longitude.

    Parameters:
        api_key (str): Google API key.
        business_name (str): Business name to query.
        city_name (str): City name for the search.
        area_name (str): Area name for the search.
        max_locations (int): Total number of locations to extract.

    Returns:
        list[dict]: List of metadata dictionaries for the locations.
    """
    import googlemaps
    import logging
    import time

    logging.info("Starting the scrape_google_maps_metadata function")
    gmaps = googlemaps.Client(key=api_key)
    location_data = []

    try:
        processed_locations = 0
        next_page_token = None

        while processed_locations < max_locations:
            # Fetch places using the API
            query = f"{business_name}, {city_name}, {area_name}"
            if next_page_token:
                response = gmaps.places(query=query, page_token=next_page_token)
            else:
                response = gmaps.places(query=query)

            # Handle API errors
            if response.get("status") != "OK":
                logging.error(f"Places API failed: {response.get('status')}")
                break

            # Process results
            results = response.get("results", [])
            for place in results:
                if processed_locations >= max_locations:
                    break

                place_id = place["place_id"]
                name = place.get("name", "N/A")
                address = place.get("formatted_address", "N/A")
                rating = place.get("rating", "N/A")
                user_ratings_total = place.get("user_ratings_total", 0)

                # Extract latitude and longitude
                geometry = place.get("geometry", {}).get("location", {})
                lat = geometry.get("lat", "N/A")
                lng = geometry.get("lng", "N/A")

                # Generate Google Maps URL
                url = f"https://www.google.com/maps/place/?q=place_id:{place_id}"

                location_data.append({
                    "Location ID": f"LOC_{processed_locations + 1}",
                    "City": city_name,
                    "Area": area_name,
                    "Name": name,
                    "Address": address,
                    "Latitude": lat,
                    "Longitude": lng,
                    "Rating": rating,
                    "Total Reviews": user_ratings_total,
                    "Place ID": place_id,
                    "Google Maps URL": url
                })

                processed_locations += 1

            # Check for pagination token
            next_page_token = response.get("next_page_token")
            if not next_page_token:
                logging.info("No more pages available.")
                break

            logging.info("Waiting for next page token to activate...")
            time.sleep(3)  # Wait for the token to become active

    except Exception as e:
        logging.error(f"An error occurred: {e}")

    return location_data

In [23]:
scrape_google_maps_metadata(api_key, "Naturals Salon", "Chennai", "Adambakkam, Brindavan Nagar", 5)

2025-01-15 16:10:57,124 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:10:57,126 - INFO - API queries_quota: 60
2025-01-15 16:10:57,551 - INFO - No more pages available.

[{'Location ID': 'LOC_1',
  'City': 'Chennai',
  'Area': 'Adambakkam, Brindavan Nagar',
  'Name': 'Naturals Salon',
  'Address': 'N37 First Flr, 2nd Street Shawalace Col, Brindavan Nagar, Adambakkam, Chennai, Tamil Nadu 600088, India',
  'Latitude': 12.9865709,
  'Longitude': 80.2051812,
  'Rating': 4.9,
  'Total Reviews': 369,
  'Place ID': 'ChIJD93nXvxdUjoRinIO5qSoRrc',
  'Google Maps URL': 'https://www.google.com/maps/place/?q=place_id:ChIJD93nXvxdUjoRinIO5qSoRrc'},
 {'Location ID': 'LOC_2',
  'City': 'Chennai',
  'Area': 'Adambakkam, Brindavan Nagar',
  'Name': 'Naturals Salon',
  'Address': 'No.16A/17, Secretariat Colony Main Road, City Link Road, above Easyday Club, Adambakkam, Chennai, Tamil Nadu 600088, India',
  'Latitude': 12.9973019,
  'Longitude': 80.2072451,
  'Rating': 4.6,
  'Total Reviews': 1368,
  'Place ID': 'ChIJP8-7AF1nUjoR3_YHwKTtq28',
  'Google Maps URL': 'https://www.google.com/maps/place/?q=place_id:ChIJP8-7AF1nUjoR3_YHwKTtq28'}]

In [29]:
df.head()

,City,Area,Address,Business Name,Status,Franchise Owner,Subscription
0,Chennai,Alwarpet,"No 220, Mowbrays Flats, TT Krishnamachari Road...",,NA,None,None
1,Chennai,Alwarpet,"No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...","Naturals Salon & Spa CP Ramaswamy road , Alwar...",NA,None,None
2,Chennai,"Adambakkam, Brindavan Nagar","N37 First Flr, 2nd Street Shawalace Col, Brind...",Naturals Salon,NA,None,None
3,Chennai,"Adambakkam,Secretariat Colony rd","No 16A/17, Secretariat Col, City Link Rd, Adam...",,NA,None,None
4,Chennai,Adyar,"No 31, Ground Floor, Ceebros Enclave, 1st Main...",,NA,None,None

In [30]:
len(df)

148

In [31]:
def process_dataframe(api_key, df):
    """
    Loop through a DataFrame and call `scrape_google_maps_metadata` for each row.

    Parameters:
        api_key (str): Google API key.
        df (pd.DataFrame): DataFrame containing 'Business Name' and 'City Name' columns.

    Returns:
        pd.DataFrame: A new DataFrame with the results.
    """
    import pandas as pd

    results = []

    for index, row in df.iterrows():
        city_name = row["City"]
        area_name = row["Area"]

        # Call the scrape_google_maps_metadata function
        data = scrape_google_maps_metadata(api_key, f"Naturals Salon", city_name, area_name, max_locations=10)  # Adjust max_locations as needed
        if data:
            results.extend(data)  # Extend the list with the results

    # Convert results to a DataFrame
    if results:
        return pd.DataFrame(results)
    else:
        print("No valid data retrieved.")
        return pd.DataFrame()  # Return an empty DataFrame if no results

In [32]:
# Process the DataFrame
result_df = process_dataframe(api_key, df)

2025-01-15 16:11:58,273 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:11:58,276 - INFO - API queries_quota: 60
2025-01-15 16:11:58,875 - INFO - No more pages available.
2025-01-15 16:11:58,881 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:11:58,883 - INFO - API queries_quota: 60
2025-01-15 16:11:59,093 - INFO - No more pages available.
2025-01-15 16:11:59,098 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:11:59,099 - INFO - API queries_quota: 60
2025-01-15 16:11:59,551 - INFO - No more pages available.
2025-01-15 16:11:59,554 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:11:59,556 - INFO - API queries_quota: 60
2025-01-15 16:12:00,000 - INFO - No more pages available.
2025-01-15 16:12:00,005 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:00,006 - INFO - API queries_quota: 60
2025-01-15 16:12:00,585 - INFO - No more pages available.
2025-01-15 16:12:00,588 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:00,590 - INFO - API queries_quota: 60
2025-01-15 16:12:01,363 - INFO - Waiting for next page token to activate...
2025-01-15 16:12:04,373 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:04,376 - INFO - API queries_quota: 60
2025-01-15 16:12:04,903 - INFO - No more pages available.
2025-01-15 16:12:04,909 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:04,910 - INFO - API queries_quota: 60
2025-01-15 16:12:05,620 - INFO - No more pages available.
2025-01-15 16:12:05,626 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:05,628 - INFO - API queries_quota: 60
2025-01-15 16:12:06,077 - INFO - No more pages available.
2025-01-15 16:12:06,083 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:06,085 - INFO - API queries_quota: 60
2025-01-15 16:12:06,526 - INFO - No more pages available.
2025-01-15 16:12:06,532 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:06,533 - INFO - API queries_quota: 60
2025-01-15 16:12:06,966 - INFO - No more pages available.
2025-01-15 16:12:06,972 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:06,974 - INFO - API queries_quota: 60
2025-01-15 16:12:07,487 - INFO - No more pages available.
2025-01-15 16:12:07,492 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:07,494 - INFO - API queries_quota: 60
2025-01-15 16:12:07,940 - INFO - No more pages available.
2025-01-15 16:12:07,946 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:07,947 - INFO - API queries_quota: 60
2025-01-15 16:12:08,379 - INFO - No more pages available.
2025-01-15 16:12:08,385 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:08,386 - INFO - API queries_quota: 60
2025-01-15 16:12:08,900 - INFO - No more pages available.
2025-01-15 16:12:08,906 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:08,908 - INFO - API queries_quota: 60
2025-01-15 16:12:09,516 - INFO - No more pages available.
2025-01-15 16:12:09,520 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:09,522 - INFO - API queries_quota: 60
2025-01-15 16:12:10,029 - INFO - No more pages available.
2025-01-15 16:12:10,035 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:10,036 - INFO - API queries_quota: 60
2025-01-15 16:12:10,588 - INFO - No more pages available.
2025-01-15 16:12:10,594 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:10,596 - INFO - API queries_quota: 60
2025-01-15 16:12:11,112 - INFO - No more pages available.
2025-01-15 16:12:11,118 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:11,119 - INFO - API queries_quota: 60
2025-01-15 16:12:11,615 - INFO - No more pages available.
2025-01-15 16:12:11,621 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:11,623 - INFO - API queries_quota: 60
2025-01-15 16:12:12,299 - INFO - No more pages available.
2025-01-15 16:12:12,305 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:12,306 - INFO - API queries_quota: 60
2025-01-15 16:12:12,968 - INFO - No more pages available.
2025-01-15 16:12:12,974 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:12,976 - INFO - API queries_quota: 60
2025-01-15 16:12:13,473 - INFO - No more pages available.
2025-01-15 16:12:13,479 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:13,481 - INFO - API queries_quota: 60
2025-01-15 16:12:13,939 - INFO - No more pages available.
2025-01-15 16:12:13,943 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:13,944 - INFO - API queries_quota: 60
2025-01-15 16:12:14,533 - INFO - No more pages available.
2025-01-15 16:12:14,539 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:14,541 - INFO - API queries_quota: 60
2025-01-15 16:12:15,062 - INFO - No more pages available.
2025-01-15 16:12:15,067 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:15,068 - INFO - API queries_quota: 60
2025-01-15 16:12:15,614 - INFO - No more pages available.
2025-01-15 16:12:15,619 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:15,621 - INFO - API queries_quota: 60
2025-01-15 16:12:16,274 - INFO - Waiting for next page token to activate...
2025-01-15 16:12:19,285 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:19,287 - INFO - API queries_quota: 60
2025-01-15 16:12:19,857 - INFO - No more pages available.
2025-01-15 16:12:19,862 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:19,864 - INFO - API queries_quota: 60
2025-01-15 16:12:20,451 - INFO - No more pages available.
2025-01-15 16:12:20,457 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:20,459 - INFO - API queries_quota: 60
2025-01-15 16:12:20,850 - INFO - No more pages available.
2025-01-15 16:12:20,854 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:20,854 - INFO - API queries_quota: 60
2025-01-15 16:12:21,517 - INFO - Waiting for next page token to activate...
2025-01-15 16:12:24,526 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:24,528 - INFO - API queries_quota: 60
2025-01-15 16:12:25,006 - INFO - No more pages available.
2025-01-15 16:12:25,011 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:25,018 - INFO - API queries_quota: 60
2025-01-15 16:12:25,528 - INFO - No more pages available.
2025-01-15 16:12:25,533 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:25,535 - INFO - API queries_quota: 60
2025-01-15 16:12:26,021 - INFO - No more pages available.
2025-01-15 16:12:26,025 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:26,026 - INFO - API queries_quota: 60
2025-01-15 16:12:26,452 - INFO - No more pages available.
2025-01-15 16:12:26,458 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:26,460 - INFO - API queries_quota: 60
2025-01-15 16:12:26,873 - INFO - No more pages available.
2025-01-15 16:12:26,878 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:26,879 - INFO - API queries_quota: 60
2025-01-15 16:12:27,382 - INFO - No more pages available.
2025-01-15 16:12:27,389 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:27,390 - INFO - API queries_quota: 60
2025-01-15 16:12:28,085 - INFO - Waiting for next page token to activate...
2025-01-15 16:12:31,094 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:31,096 - INFO - API queries_quota: 60
2025-01-15 16:12:31,629 - INFO - No more pages available.
2025-01-15 16:12:31,631 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:31,632 - INFO - API queries_quota: 60
2025-01-15 16:12:32,337 - INFO - No more pages available.
2025-01-15 16:12:32,340 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:32,341 - INFO - API queries_quota: 60
2025-01-15 16:12:32,914 - INFO - No more pages available.
2025-01-15 16:12:32,920 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:32,921 - INFO - API queries_quota: 60
2025-01-15 16:12:33,375 - INFO - No more pages available.
2025-01-15 16:12:33,380 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:33,381 - INFO - API queries_quota: 60
2025-01-15 16:12:33,857 - INFO - No more pages available.
2025-01-15 16:12:33,863 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:33,865 - INFO - API queries_quota: 60
2025-01-15 16:12:34,347 - INFO - No more pages available.
2025-01-15 16:12:34,352 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:34,354 - INFO - API queries_quota: 60
2025-01-15 16:12:34,910 - INFO - No more pages available.
2025-01-15 16:12:34,916 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:34,918 - INFO - API queries_quota: 60
2025-01-15 16:12:35,488 - INFO - No more pages available.
2025-01-15 16:12:35,492 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:35,493 - INFO - API queries_quota: 60
2025-01-15 16:12:36,036 - INFO - No more pages available.
2025-01-15 16:12:36,040 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:36,041 - INFO - API queries_quota: 60
2025-01-15 16:12:36,621 - INFO - No more pages available.
2025-01-15 16:12:36,625 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:36,627 - INFO - API queries_quota: 60
2025-01-15 16:12:37,218 - INFO - No more pages available.
2025-01-15 16:12:37,224 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:37,226 - INFO - API queries_quota: 60
2025-01-15 16:12:37,734 - INFO - No more pages available.
2025-01-15 16:12:37,737 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:37,739 - INFO - API queries_quota: 60
2025-01-15 16:12:38,201 - INFO - No more pages available.
2025-01-15 16:12:38,206 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:38,207 - INFO - API queries_quota: 60
2025-01-15 16:12:38,651 - INFO - No more pages available.
2025-01-15 16:12:38,657 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:38,658 - INFO - API queries_quota: 60
2025-01-15 16:12:39,184 - INFO - No more pages available.
2025-01-15 16:12:39,190 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:39,192 - INFO - API queries_quota: 60
2025-01-15 16:12:39,723 - INFO - No more pages available.
2025-01-15 16:12:39,729 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:39,731 - INFO - API queries_quota: 60
2025-01-15 16:12:40,522 - INFO - No more pages available.
2025-01-15 16:12:40,528 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:40,530 - INFO - API queries_quota: 60
2025-01-15 16:12:41,036 - INFO - No more pages available.
2025-01-15 16:12:41,041 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:41,042 - INFO - API queries_quota: 60
2025-01-15 16:12:41,609 - INFO - No more pages available.
2025-01-15 16:12:41,616 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:41,617 - INFO - API queries_quota: 60
2025-01-15 16:12:42,118 - INFO - No more pages available.
2025-01-15 16:12:42,123 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:42,125 - INFO - API queries_quota: 60
2025-01-15 16:12:42,671 - INFO - No more pages available.
2025-01-15 16:12:42,677 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:42,679 - INFO - API queries_quota: 60
2025-01-15 16:12:43,224 - INFO - No more pages available.
2025-01-15 16:12:43,230 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:43,231 - INFO - API queries_quota: 60
2025-01-15 16:12:43,726 - INFO - No more pages available.
2025-01-15 16:12:43,732 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:43,733 - INFO - API queries_quota: 60
2025-01-15 16:12:44,268 - INFO - No more pages available.
2025-01-15 16:12:44,273 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:44,275 - INFO - API queries_quota: 60
2025-01-15 16:12:44,842 - INFO - No more pages available.
2025-01-15 16:12:44,848 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:44,849 - INFO - API queries_quota: 60
2025-01-15 16:12:45,592 - INFO - No more pages available.
2025-01-15 16:12:45,598 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:45,600 - INFO - API queries_quota: 60
2025-01-15 16:12:46,155 - INFO - No more pages available.
2025-01-15 16:12:46,158 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:46,159 - INFO - API queries_quota: 60
2025-01-15 16:12:46,746 - INFO - No more pages available.
2025-01-15 16:12:46,752 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:46,754 - INFO - API queries_quota: 60
2025-01-15 16:12:47,227 - INFO - No more pages available.
2025-01-15 16:12:47,233 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:47,235 - INFO - API queries_quota: 60
2025-01-15 16:12:47,690 - INFO - No more pages available.
2025-01-15 16:12:47,695 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:47,696 - INFO - API queries_quota: 60
2025-01-15 16:12:48,255 - INFO - No more pages available.
2025-01-15 16:12:48,261 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:48,262 - INFO - API queries_quota: 60
2025-01-15 16:12:48,735 - INFO - No more pages available.
2025-01-15 16:12:48,740 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:48,742 - INFO - API queries_quota: 60
2025-01-15 16:12:49,251 - INFO - No more pages available.
2025-01-15 16:12:49,256 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:49,258 - INFO - API queries_quota: 60
2025-01-15 16:12:49,710 - INFO - No more pages available.
2025-01-15 16:12:49,714 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:49,716 - INFO - API queries_quota: 60
2025-01-15 16:12:50,280 - INFO - No more pages available.
2025-01-15 16:12:50,286 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:50,289 - INFO - API queries_quota: 60
2025-01-15 16:12:50,848 - INFO - No more pages available.
2025-01-15 16:12:50,851 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:50,852 - INFO - API queries_quota: 60
2025-01-15 16:12:51,264 - INFO - No more pages available.
2025-01-15 16:12:51,270 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:51,272 - INFO - API queries_quota: 60
2025-01-15 16:12:51,804 - INFO - No more pages available.
2025-01-15 16:12:51,810 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:51,811 - INFO - API queries_quota: 60
2025-01-15 16:12:52,352 - INFO - No more pages available.
2025-01-15 16:12:52,357 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:52,359 - INFO - API queries_quota: 60
2025-01-15 16:12:52,794 - INFO - No more pages available.
2025-01-15 16:12:52,799 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:52,800 - INFO - API queries_quota: 60
2025-01-15 16:12:53,313 - INFO - No more pages available.
2025-01-15 16:12:53,318 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:53,319 - INFO - API queries_quota: 60
2025-01-15 16:12:53,843 - INFO - No more pages available.
2025-01-15 16:12:53,847 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:53,849 - INFO - API queries_quota: 60
2025-01-15 16:12:54,296 - INFO - No more pages available.
2025-01-15 16:12:54,299 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:54,301 - INFO - API queries_quota: 60
2025-01-15 16:12:54,772 - INFO - No more pages available.
2025-01-15 16:12:54,776 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:54,778 - INFO - API queries_quota: 60
2025-01-15 16:12:55,422 - INFO - No more pages available.
2025-01-15 16:12:55,425 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:55,427 - INFO - API queries_quota: 60
2025-01-15 16:12:55,969 - INFO - No more pages available.
2025-01-15 16:12:55,974 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:55,975 - INFO - API queries_quota: 60
2025-01-15 16:12:56,460 - INFO - No more pages available.
2025-01-15 16:12:56,465 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:56,467 - INFO - API queries_quota: 60
2025-01-15 16:12:57,039 - INFO - No more pages available.
2025-01-15 16:12:57,043 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:57,045 - INFO - API queries_quota: 60
2025-01-15 16:12:57,573 - INFO - No more pages available.
2025-01-15 16:12:57,578 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:57,580 - INFO - API queries_quota: 60
2025-01-15 16:12:58,137 - INFO - No more pages available.
2025-01-15 16:12:58,141 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:58,143 - INFO - API queries_quota: 60
2025-01-15 16:12:58,565 - INFO - No more pages available.
2025-01-15 16:12:58,569 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:58,571 - INFO - API queries_quota: 60
2025-01-15 16:12:59,176 - INFO - No more pages available.
2025-01-15 16:12:59,181 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:59,182 - INFO - API queries_quota: 60
2025-01-15 16:12:59,696 - INFO - No more pages available.
2025-01-15 16:12:59,702 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:12:59,703 - INFO - API queries_quota: 60
2025-01-15 16:13:00,218 - INFO - No more pages available.
2025-01-15 16:13:00,224 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:00,226 - INFO - API queries_quota: 60
2025-01-15 16:13:00,824 - INFO - No more pages available.
2025-01-15 16:13:00,828 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:00,829 - INFO - API queries_quota: 60
2025-01-15 16:13:01,292 - INFO - No more pages available.
2025-01-15 16:13:01,297 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:01,299 - INFO - API queries_quota: 60
2025-01-15 16:13:01,735 - INFO - No more pages available.
2025-01-15 16:13:01,741 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:01,744 - INFO - API queries_quota: 60
2025-01-15 16:13:02,325 - INFO - No more pages available.
2025-01-15 16:13:02,329 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:02,331 - INFO - API queries_quota: 60
2025-01-15 16:13:02,861 - INFO - No more pages available.
2025-01-15 16:13:02,865 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:02,867 - INFO - API queries_quota: 60
2025-01-15 16:13:03,428 - INFO - No more pages available.
2025-01-15 16:13:03,433 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:03,434 - INFO - API queries_quota: 60
2025-01-15 16:13:03,912 - INFO - No more pages available.
2025-01-15 16:13:03,917 - INFO - Starting the scrape_google_maps_metadata function
2025-01-15 16:13:03,919 - INFO - API queries_quota: 60
2025-01-15 16:13:04,604 - INFO - No more pages available.
2025-01-15 16:13:04,609 - INFO - Starting the scrape_google_maps_metadata function

In [33]:
len(result_df)

472

In [34]:
result_df = result_df.drop_duplicates(subset=['Place ID'])

In [35]:
len(result_df)

178

In [36]:
result_df.head()

,Location ID,City,Area,Name,Address,Latitude,Longitude,Rating,Total Reviews,Place ID,Google Maps URL
0,LOC_1,Chennai,Alwarpet,Naturals Signature Salon Alwarpet,"No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1097,ChIJB0quoslnUjoRf_vm8BiGHsM,https://www.google.com/maps/place/?q=place_id:...
1,LOC_2,Chennai,Alwarpet,Naturals Lounge TTK,"No.220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043691,80.259478,4.6,669,ChIJfwi_pjZmUjoRtNJzL20D2-A,https://www.google.com/maps/place/?q=place_id:...
2,LOC_3,Chennai,Alwarpet,Naturals Signature Salon,"No: 24-25, Venkatakrishna Rd, above Spencer's ...",13.026759,80.261401,4.8,2834,ChIJT8VLUspnUjoRa_HrTUzVpa4,https://www.google.com/maps/place/?q=place_id:...
3,LOC_4,Chennai,Alwarpet,Naturals Salon,"28/10, Venkataswamy St, opposite Apollo Pharma...",13.030194,80.275652,4.8,439,ChIJ05jy-4dnUjoR8hWlWTOTQok,https://www.google.com/maps/place/?q=place_id:...
4,LOC_5,Chennai,Alwarpet,Naturals Salon,"No 220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043618,80.259485,5.0,1,ChIJ1cEdFYpnUjoRBTQevSN3-mU,https://www.google.com/maps/place/?q=place_id:...

In [37]:
result_df["Total Reviews"].sum()

183726

In [38]:
result_df["Rating"].isna().sum()

0

In [39]:
(result_df['Total Reviews'] == 0).sum()

2

In [40]:
result_df["Name"].value_counts()

Name
Naturals Salon                                                  102
Naturals Signature Salon                                         15
Naturals                                                          3
Naturals Beauty Academy                                           2
Naturals salon                                                    2
Naturals Unisex Salon ECR Link Road                               1
Studieo7 Family Salon & Bridal Studio - Nanganallur               1
Natural Hair & Beauty Salon and Spa                               1
Naturals salon (Exclusive Women's)- Sowcarpet                     1
Natural's Beauty Parlour                                          1
Naturals Signature Salon Alwarpet                                 1
Naturals Unisex Salon Sholinganallur                              1
Naturals Salon & Spa Siruseri                                     1
Shree Naturals                                                    1
NATURALS SALON AND SPA                                            1
Naturals Salon & Spa , Saidapet                                   1
Naturals Makeup Hub                                               1
Allure Unisex Salon                                               1
Naturals Corporate Office (Groom India salon & spa pvt. ltd)      1
Naturals Salon & Spa Velachery                                    1
Naturals Salon W- Women's exclsuive                               1
Toni&Guy Hairdressing, Phoenix Market City                        1
Knotty Naturals                                                   1
simply natural hair braiding shop                                 1
Locs by Nature Salon                                              1
Bleu Stella                                                       1
Eden DC Salon                                                     1
Cole Stevens Salon                                                1
Salon Revive                                                      1
Image Hair Salon                                                  1
Signature Image Salon                                             1
Naturals Unisex Hair And Style Salon                              1
Naturals Salon & Spa Gowrivakkam                                  1
Naturals Signature perungudi                                      1
Naturals Salon & Spa Neelankarai                                  1
Naturals Signature Salon Rajakilpakkam                            1
Naturals Salon Anna Nagar West Extension                          1
Naturals Signature Salon & Spa Annanagar West                     1
Naturals Signature Salon Ashok Nagar                              1
Natural Beauty Parlour                                            1
Naturals Salon & Spa, Pattabiram                                  1
New Naturaas Premium Family Salon                                 1
SK Naturals Beauty Parlour                                        1
Naturals Thiruverkadu                                             1
Naturals Salon & Spa Chinmaya Nagar                               1
Naturals Signature Salon Hasthinapuram                            1
Naturals Salon & Spa Chromepet                                    1
Naturals Salon Egmore Alsa Mall                                   1
Naturals signature Salon                                          1
Naturals Signature Salon radha krishnan salai                     1
Naturals Unisex Salon - Kodungaiyur                               1
JP Naturals                                                       1
Naturals Salon & Spa Karayanchavadi                               1
Naturals Salon & Spa Poonamallee                                  1
Page 3 Luxury Salon Kilpauk                                       1
Natural green beauty salon & Bridal studio                        1
Naturals Sithalapakkam                                            1
Naturals Lounge TTK                                               1
Inizio Hair Salon                                                 1
Name: count, dtype: int64

In [74]:
# List of allowed values
not_allowed_names = ["Shree Naturals", "GREEN TRENDS PERUNGALATHUR", "Sun Naturals Unisex Salon And Spa", "Studieo7 Family Salon & Bridal Studio - Nanganallur",
                    "Allure Unisex Salon", "Isha", "Green Trends Unisex Hair & Style Salon", "Page 3 Luxury Salon Kilpauk", "Vinodhbamaa Makeup Artistry | Beautician Course in Chennai | Makeup Training Academy | Makeup course",
                    "Naturals Corporate Office", "Toni&Guy Hairdressing, Phoenix Market City", "JP Naturals", "Inizio Hair Salon",
                    "simply natural hair braiding shop", "Locs by Nature Salon", "Bleu Stella", "Eden DC Salon", "Cole Stevens Salon",
                    "Salon Revive", "Image Hair Salon", "Signature Image Salon", "SK Naturals Beauty Parlour", "Naturals Beauty Academy",
                    "Knotty Naturals", "New Naturaas Premium Family Salon", "Natural green beauty salon & Bridal studio",
                    "Naturals Corporate Office (Groom India salon & spa pvt. ltd)", "Naturals Makeup Hub", "Natural Beauty Parlour"]

# Keep rows where 'name' is in the list of allowed values
result_df = result_df[~result_df['Name'].isin(not_allowed_names)]

In [77]:
len(result_df)

154

In [78]:
result_df.head()

,Location ID,City,Area,Name,Address,Latitude,Longitude,Rating,Total Reviews,Place ID,Google Maps URL
0,LOC_1,Chennai,Alwarpet,Naturals Signature Salon Alwarpet,"No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1097,ChIJB0quoslnUjoRf_vm8BiGHsM,https://www.google.com/maps/place/?q=place_id:...
1,LOC_2,Chennai,Alwarpet,Naturals Lounge TTK,"No.220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043691,80.259478,4.6,669,ChIJfwi_pjZmUjoRtNJzL20D2-A,https://www.google.com/maps/place/?q=place_id:...
2,LOC_3,Chennai,Alwarpet,Naturals Signature Salon,"No: 24-25, Venkatakrishna Rd, above Spencer's ...",13.026759,80.261401,4.8,2834,ChIJT8VLUspnUjoRa_HrTUzVpa4,https://www.google.com/maps/place/?q=place_id:...
3,LOC_4,Chennai,Alwarpet,Naturals Salon,"28/10, Venkataswamy St, opposite Apollo Pharma...",13.030194,80.275652,4.8,439,ChIJ05jy-4dnUjoR8hWlWTOTQok,https://www.google.com/maps/place/?q=place_id:...
4,LOC_5,Chennai,Alwarpet,Naturals Salon,"No 220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043618,80.259485,5.0,1,ChIJ1cEdFYpnUjoRBTQevSN3-mU,https://www.google.com/maps/place/?q=place_id:...

In [76]:
result_df["Name"].value_counts()

Name
Naturals Salon                                   102
Naturals Signature Salon                          15
Naturals                                           3
Naturals salon                                     2
Naturals Signature Salon Alwarpet                  1
Naturals Salon & Spa , Saidapet                    1
Naturals Salon & Spa Gowrivakkam                   1
Naturals Salon & Spa Neelankarai                   1
Naturals Signature perungudi                       1
Naturals Salon & Spa Velachery                     1
Naturals Unisex Hair And Style Salon               1
Naturals Salon & Spa Siruseri                      1
NATURALS SALON AND SPA                             1
Naturals Salon & Spa Poonamallee                   1
Naturals Unisex Salon Sholinganallur               1
Naturals Unisex Salon ECR Link Road                1
Natural's Beauty Parlour                           1
Naturals salon (Exclusive Women's)- Sowcarpet      1
Natural Hair & Beauty Salon and Spa                1
Naturals Sithalapakkam                             1
Naturals Unisex Salon - Kodungaiyur                1
Naturals Salon & Spa Karayanchavadi                1
Naturals Lounge TTK                                1
Naturals Signature Salon radha krishnan salai      1
Naturals signature Salon                           1
Naturals Salon Egmore Alsa Mall                    1
Naturals Salon & Spa Chromepet                     1
Naturals Signature Salon Hasthinapuram             1
Naturals Salon & Spa Chinmaya Nagar                1
Naturals Thiruverkadu                              1
Naturals Salon & Spa, Pattabiram                   1
Naturals Signature Salon Ashok Nagar               1
Naturals Signature Salon & Spa Annanagar West      1
Naturals Salon Anna Nagar West Extension           1
Naturals Signature Salon Rajakilpakkam             1
Naturals Salon W- Women's exclsuive                1
Name: count, dtype: int64

In [79]:
result_df['full_location'] = result_df['City'] + " " + result_df['Area'] + result_df['Name']

In [80]:
result_df.to_csv("data/naturals_chennai_locations_metadata.csv")
result_df['Google Maps URL'].to_csv('data/naturals_chennai_maps_urls.txt', index=False)

In [81]:
result_df.head()

,Location ID,City,Area,Name,Address,Latitude,Longitude,Rating,Total Reviews,Place ID,Google Maps URL,full_location
0,LOC_1,Chennai,Alwarpet,Naturals Signature Salon Alwarpet,"No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1097,ChIJB0quoslnUjoRf_vm8BiGHsM,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Signature Salon Alwarpet
1,LOC_2,Chennai,Alwarpet,Naturals Lounge TTK,"No.220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043691,80.259478,4.6,669,ChIJfwi_pjZmUjoRtNJzL20D2-A,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Lounge TTK
2,LOC_3,Chennai,Alwarpet,Naturals Signature Salon,"No: 24-25, Venkatakrishna Rd, above Spencer's ...",13.026759,80.261401,4.8,2834,ChIJT8VLUspnUjoRa_HrTUzVpa4,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Signature Salon
3,LOC_4,Chennai,Alwarpet,Naturals Salon,"28/10, Venkataswamy St, opposite Apollo Pharma...",13.030194,80.275652,4.8,439,ChIJ05jy-4dnUjoR8hWlWTOTQok,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Salon
4,LOC_5,Chennai,Alwarpet,Naturals Salon,"No 220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043618,80.259485,5.0,1,ChIJ1cEdFYpnUjoRBTQevSN3-mU,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Salon

### Read Data

In [83]:
import pandas as pd

df = pd.read_csv("data/naturals_chennai_locations_metadata.csv")

In [84]:
len(df)

154

In [85]:
df.head()

,Unnamed: 0,Location ID,City,Area,Name,Address,Latitude,Longitude,Rating,Total Reviews,Place ID,Google Maps URL,full_location
0,0,LOC_1,Chennai,Alwarpet,Naturals Signature Salon Alwarpet,"No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1097,ChIJB0quoslnUjoRf_vm8BiGHsM,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Signature Salon Alwarpet
1,1,LOC_2,Chennai,Alwarpet,Naturals Lounge TTK,"No.220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043691,80.259478,4.6,669,ChIJfwi_pjZmUjoRtNJzL20D2-A,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Lounge TTK
2,2,LOC_3,Chennai,Alwarpet,Naturals Signature Salon,"No: 24-25, Venkatakrishna Rd, above Spencer's ...",13.026759,80.261401,4.8,2834,ChIJT8VLUspnUjoRa_HrTUzVpa4,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Signature Salon
3,3,LOC_4,Chennai,Alwarpet,Naturals Salon,"28/10, Venkataswamy St, opposite Apollo Pharma...",13.030194,80.275652,4.8,439,ChIJ05jy-4dnUjoR8hWlWTOTQok,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Salon
4,4,LOC_5,Chennai,Alwarpet,Naturals Salon,"No 220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043618,80.259485,5.0,1,ChIJ1cEdFYpnUjoRBTQevSN3-mU,https://www.google.com/maps/place/?q=place_id:...,Chennai AlwarpetNaturals Salon