In [1]:
import pandas as pd
from openai import OpenAI
import os
from dotenv import load_dotenv
from tqdm import tqdm
import time

In [2]:
# Load environment variables from the .env file
load_dotenv(".env")

True

In [3]:
df = pd.read_csv("googlemaps-scraper/data/newest_gm_reviews_2025-01-13.csv")

In [4]:
len(df)

31149

In [5]:
df.head(3)

,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,place_id
0,ChdDSUhNMG9nS0VJQ0FnSUNfMVBHRTh3RRAB,Saiyda,13 hours ago,2025-01-13 15:59:48.626486,2025-01-13 15:59:48.626537,5.0,kiruthika srinivasan,0,ChIJB0quoslnUjoRf_vm8BiGHsM
1,ChZDSUhNMG9nS0VJQ0FnSURmMzVfZElnEAE,Good waxing and face massage service by Shaila...,2 days ago,2025-01-11 15:59:48.626770,2025-01-13 15:59:48.626799,4.0,Yamini Srinivasan,0,ChIJB0quoslnUjoRf_vm8BiGHsM
2,ChZDSUhNMG9nS0VJQ0FnSUQtb05tZ2J3EAE,I've been coming here for the last 10 years an...,2 days ago,2025-01-11 15:59:48.626887,2025-01-13 15:59:48.626911,5.0,Pinky Kohli,9,ChIJB0quoslnUjoRf_vm8BiGHsM

In [6]:
df["retrieval_date"].value_counts()

retrieval_date
2025-01-13 15:59:48.626537    1
2025-01-13 19:38:52.743569    1
2025-01-13 19:39:05.674448    1
2025-01-13 19:39:05.674349    1
2025-01-13 19:39:05.674247    1
                             ..
2025-01-13 17:47:10.483319    1
2025-01-13 17:47:10.483182    1
2025-01-13 17:47:06.254778    1
2025-01-13 17:47:06.254673    1
2025-01-13 21:28:57.565981    1
Name: count, Length: 31149, dtype: int64

In [7]:
len(df["place_id"].value_counts())

43

In [8]:
df["review_date"].value_counts()

review_date
2025-01-13 15:59:48.626486    1
2024-06-13 19:38:52.743540    1
2024-05-13 19:39:05.674420    1
2024-05-13 19:39:05.674322    1
2024-05-13 19:39:05.674219    1
                             ..
2024-02-13 17:47:10.483285    1
2024-02-13 17:47:10.483099    1
2024-02-13 17:47:06.254749    1
2024-02-13 17:47:06.254644    1
2024-04-13 21:28:57.565938    1
Name: count, Length: 31149, dtype: int64

In [9]:
df['caption'].isna().sum()

np.int64(8093)

In [10]:
df = df[df['caption'].notna()]

In [11]:
len(df)

23056

In [12]:
df.head(3)

,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,place_id
0,ChdDSUhNMG9nS0VJQ0FnSUNfMVBHRTh3RRAB,Saiyda,13 hours ago,2025-01-13 15:59:48.626486,2025-01-13 15:59:48.626537,5.0,kiruthika srinivasan,0,ChIJB0quoslnUjoRf_vm8BiGHsM
1,ChZDSUhNMG9nS0VJQ0FnSURmMzVfZElnEAE,Good waxing and face massage service by Shaila...,2 days ago,2025-01-11 15:59:48.626770,2025-01-13 15:59:48.626799,4.0,Yamini Srinivasan,0,ChIJB0quoslnUjoRf_vm8BiGHsM
2,ChZDSUhNMG9nS0VJQ0FnSUQtb05tZ2J3EAE,I've been coming here for the last 10 years an...,2 days ago,2025-01-11 15:59:48.626887,2025-01-13 15:59:48.626911,5.0,Pinky Kohli,9,ChIJB0quoslnUjoRf_vm8BiGHsM

In [13]:
reviews = df["caption"]

In [14]:
len(reviews)

23056

In [15]:
reviews

0                                                   Saiyda
1        Good waxing and face massage service by Shaila...
2        I've been coming here for the last 10 years an...
5        Excellent team.. well done guys. 👍. Continue t...
7              Good and neat service by kalpana and rathna
                               ...
31144    Services was very good. Prabhakaran did a good...
31145    Jeevitha attended soo good and the service was...
31146                     Good service by geetha staff 😇 …
31147                Good service from jeevitha. Thank you
31148    Prabhakaran I did facial and beard trimmer ful...
Name: caption, Length: 23056, dtype: object

In [16]:
# Function to analyze sentiment
def analyze_sentiment(text):
    """
    Analyze the sentiment of a given text using OpenAI's GPT models.

    Args:
        text (str): The text to analyze.

    Returns:
        str: The sentiment analysis result (e.g., "Positive", "Negative", "Neutral").
    """
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
    
    try:
        response = client.chat.completions.create(
            model="gpt-4",  # Replace with the model you prefer
            messages=[
               {"role": "user", "content": f"""
                    Please classify the sentiment of the following text as Positive, Negative, Neutral, or Mixed, adhering to the following rules:
                    
                    1. If the text only contains a name (e.g., "John", "Sarah"), classify it as **Neutral**.
                    2. If there are spelling errors, correct them before performing the sentiment classification.
                    3. If the text is not in English, translate it to English before performing the sentiment classification.
                    4. Your classification output must strictly be one of the following: **Positive**, **Negative**, **Neutral**, or **Mixed**.
                    
                    Text: {text}
                    """}
            ],
            temperature=0.0
        )

        sentiment = response.choices[0].message.content
        return sentiment
        
    except Exception as e:
        print(f"Error during sentiment analysis: {e}")
        return None

In [17]:
response = analyze_sentiment(reviews[1])

In [18]:
response

'Positive'

In [19]:
reviews[1]

'Good waxing and face massage service by Shaila. Amazing hospitality'

In [20]:
analyze_sentiment("service was good, but bathroom was not clean")

'Mixed'

In [21]:
tqdm.pandas()

In [29]:
def analyze_sentiment_batch(texts):
    """
    Analyze sentiment for a batch of texts using OpenAI API.

    Args:
        texts (list of str): List of texts to analyze.

    Returns:
        list of str: List of sentiment analysis results.
    """
    from openai import OpenAI
    import os

    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
    
    try:
        results = []
        for text in texts:
            messages = [
                {
                    "role": "user",
                    "content": f"""
                    Please classify the sentiment of the following text as Positive, Negative, Neutral, or Mixed, adhering to the following rules:
                    
                    1. If the text only contains a name (e.g., "John", "Sarah"), classify it as **Neutral**.
                    2. If there are spelling errors, correct them before performing the sentiment classification.
                    3. If the text is not in English, translate it to English before performing the sentiment classification.
                    4. Your classification output must strictly be one of the following: **Positive**, **Negative**, **Neutral**, or **Mixed**.
                    
                    Text: {text}
                    """
                }
            ]
            
            response = client.chat.completions.create(
                model="gpt-4",  # Use "gpt-3.5-turbo" for faster response if accuracy is acceptable
                messages=messages,
                temperature=0.0
            )
            
            # Append the result to the results list
            result = response.choices[0].message.content.strip()
            results.append(result)
        
        return results

    except Exception as e:
        print(f"Error during sentiment analysis: {e}")
        return [None] * len(texts)

In [30]:
# tqdm.pandas()

# batch_size = 5

# sample_df['sentiment'] = None

# for i in tqdm(range(0, len(sample_df), batch_size), desc="Processing Batches"):
#     batch = sample_df['caption'].iloc[i:i+batch_size]
#     sentiments = analyze_sentiment_batch(batch.tolist())
#     sample_df.loc[batch.index, 'sentiment'] = sentiments

In [31]:
# List of texts
texts = df['caption'].tolist()  # Replace with your actual list if it's not from a DataFrame
batch_size = 5
sentiments = []

In [32]:
len(texts)

23056

In [33]:
from tqdm import tqdm

# Process the texts in batches
for i in tqdm(range(0, len(texts), batch_size), desc="Processing Batches"):
    batch = texts[i:i + batch_size]  # Extract batch of texts
    batch_sentiments = analyze_sentiment_batch(batch)  # Call your batch sentiment analysis function
    sentiments.extend(batch_sentiments)  # Append results to the sentiments list

Processing Batches:  66%|█████████▉     | 3043/4612 [2:37:04<1:37:58,  3.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3045/4612 [2:37:13<1:44:28,  4.00s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3047/4612 [2:37:25<2:10:47,  5.01s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3048/4612 [2:37:26<1:44:09,  4.00s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3049/4612 [2:37:28<1:25:19,  3.28s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3050/4612 [2:37:30<1:13:04,  2.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3051/4612 [2:37:31<1:04:24,  2.48s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▏     | 3052/4612 [2:37:33<57:24,  2.21s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3053/4612 [2:37:35<52:51,  2.03s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3054/4612 [2:37:41<1:25:50,  3.31s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3055/4612 [2:37:43<1:13:35,  2.84s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3056/4612 [2:37:44<1:03:38,  2.45s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3057/4612 [2:37:50<1:30:43,  3.50s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3058/4612 [2:37:52<1:15:23,  2.91s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|█████████▉     | 3059/4612 [2:37:53<1:04:26,  2.49s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3060/4612 [2:37:55<57:53,  2.24s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3061/4612 [2:37:57<54:28,  2.11s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3062/4612 [2:37:59<52:42,  2.04s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3063/4612 [2:38:00<49:56,  1.93s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3064/4612 [2:38:02<46:57,  1.82s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3065/4612 [2:38:03<45:42,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  66%|███████████▎     | 3066/4612 [2:38:05<43:29,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3067/4612 [2:38:06<42:40,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3068/4612 [2:38:08<42:27,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3069/4612 [2:38:10<42:24,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3070/4612 [2:38:11<42:20,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3071/4612 [2:38:13<42:58,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3072/4612 [2:38:15<41:37,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3073/4612 [2:38:16<41:43,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3074/4612 [2:38:18<41:52,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3075/4612 [2:38:20<42:40,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3076/4612 [2:38:21<41:26,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3077/4612 [2:38:23<40:56,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3078/4612 [2:38:24<40:30,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3079/4612 [2:38:26<40:15,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3080/4612 [2:38:28<40:58,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3081/4612 [2:38:29<41:43,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3082/4612 [2:38:31<41:25,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3083/4612 [2:38:32<41:25,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3084/4612 [2:38:34<40:20,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▎     | 3085/4612 [2:38:36<40:39,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3086/4612 [2:38:37<41:23,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3087/4612 [2:38:39<42:04,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3088/4612 [2:38:41<41:19,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3089/4612 [2:38:42<40:36,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3090/4612 [2:38:44<39:43,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3091/4612 [2:38:45<40:44,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3092/4612 [2:38:47<41:29,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3093/4612 [2:38:49<41:42,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3094/4612 [2:38:51<44:02,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3095/4612 [2:38:52<44:53,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3096/4612 [2:38:54<45:29,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3097/4612 [2:38:56<47:05,  1.87s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3098/4612 [2:38:58<47:33,  1.88s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3099/4612 [2:39:00<45:43,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3100/4612 [2:39:01<43:46,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3101/4612 [2:39:03<42:30,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3102/4612 [2:39:05<41:34,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3103/4612 [2:39:06<41:15,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3104/4612 [2:39:08<42:00,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3105/4612 [2:39:10<42:16,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3106/4612 [2:39:11<41:24,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3107/4612 [2:39:13<41:20,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3108/4612 [2:39:15<41:15,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3109/4612 [2:39:16<41:03,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3110/4612 [2:39:18<40:35,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3111/4612 [2:39:20<41:41,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3112/4612 [2:39:21<40:32,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  67%|███████████▍     | 3113/4612 [2:39:23<41:01,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▍     | 3114/4612 [2:39:24<40:17,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▍     | 3115/4612 [2:39:26<39:32,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▍     | 3116/4612 [2:39:28<40:27,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▍     | 3117/4612 [2:39:29<41:16,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▍     | 3118/4612 [2:39:31<41:01,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▍     | 3119/4612 [2:39:33<41:32,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3120/4612 [2:39:34<41:19,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3121/4612 [2:39:36<42:03,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3122/4612 [2:39:38<41:54,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3123/4612 [2:39:39<40:54,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3124/4612 [2:39:41<41:20,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3125/4612 [2:39:43<40:40,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3126/4612 [2:39:44<40:47,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3127/4612 [2:39:46<39:26,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3128/4612 [2:39:47<40:23,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3129/4612 [2:39:49<39:46,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3130/4612 [2:39:51<40:54,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3131/4612 [2:39:52<41:41,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3132/4612 [2:39:54<40:31,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3133/4612 [2:39:56<41:03,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3134/4612 [2:39:57<39:52,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3135/4612 [2:39:59<40:16,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3136/4612 [2:40:01<40:27,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3137/4612 [2:40:02<40:34,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3138/4612 [2:40:04<40:34,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3139/4612 [2:40:05<39:43,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3140/4612 [2:40:07<39:20,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3141/4612 [2:40:09<38:56,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3142/4612 [2:40:10<39:45,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3143/4612 [2:40:12<39:22,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3144/4612 [2:40:14<40:21,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3145/4612 [2:40:15<40:12,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3146/4612 [2:40:17<40:20,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3147/4612 [2:40:19<41:53,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3148/4612 [2:40:20<41:20,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3149/4612 [2:40:22<41:24,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3150/4612 [2:40:24<39:25,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3151/4612 [2:40:25<38:41,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3152/4612 [2:40:27<38:33,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▌     | 3153/4612 [2:40:28<38:51,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▋     | 3154/4612 [2:40:30<39:25,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▋     | 3155/4612 [2:40:32<40:42,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▋     | 3156/4612 [2:40:33<40:14,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▋     | 3157/4612 [2:40:35<39:06,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▋     | 3158/4612 [2:40:36<38:41,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  68%|███████████▋     | 3159/4612 [2:40:38<40:04,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3160/4612 [2:40:40<41:11,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3161/4612 [2:40:42<40:26,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3162/4612 [2:40:43<40:18,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3163/4612 [2:40:45<39:37,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3164/4612 [2:40:46<38:58,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3165/4612 [2:40:48<38:17,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3166/4612 [2:40:50<38:45,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3167/4612 [2:40:51<38:47,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3168/4612 [2:40:53<38:55,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3169/4612 [2:40:55<39:32,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3170/4612 [2:40:56<39:33,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3171/4612 [2:40:58<39:36,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3172/4612 [2:40:59<39:09,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3173/4612 [2:41:01<40:00,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3174/4612 [2:41:03<38:52,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3175/4612 [2:41:04<39:07,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3176/4612 [2:41:06<37:48,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3177/4612 [2:41:07<36:59,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3178/4612 [2:41:09<38:13,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3179/4612 [2:41:11<38:15,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3180/4612 [2:41:12<37:38,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3181/4612 [2:41:14<38:21,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3182/4612 [2:41:15<38:16,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3183/4612 [2:41:17<38:48,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3184/4612 [2:41:19<39:58,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3185/4612 [2:41:21<40:32,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3186/4612 [2:41:22<39:38,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▋     | 3187/4612 [2:41:24<38:53,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3188/4612 [2:41:25<38:53,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3189/4612 [2:41:27<39:24,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3190/4612 [2:41:29<40:02,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3191/4612 [2:41:31<40:41,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3192/4612 [2:41:32<40:10,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3193/4612 [2:41:34<40:05,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3194/4612 [2:41:36<39:56,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3195/4612 [2:41:37<39:07,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3196/4612 [2:41:39<39:02,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3197/4612 [2:41:41<38:35,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3198/4612 [2:41:42<38:04,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3199/4612 [2:41:44<37:43,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3200/4612 [2:41:45<37:20,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3201/4612 [2:41:47<38:13,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3202/4612 [2:41:49<38:41,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3203/4612 [2:41:50<38:39,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3204/4612 [2:41:52<37:34,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  69%|███████████▊     | 3205/4612 [2:41:54<38:25,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3206/4612 [2:41:55<39:26,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3207/4612 [2:41:57<39:17,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3208/4612 [2:41:59<39:33,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3209/4612 [2:42:00<38:59,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3210/4612 [2:42:02<37:49,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3211/4612 [2:42:03<37:22,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3212/4612 [2:42:05<36:15,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3213/4612 [2:42:06<37:06,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3214/4612 [2:42:08<38:13,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3215/4612 [2:42:10<39:12,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3216/4612 [2:42:12<38:45,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3217/4612 [2:42:13<39:21,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3218/4612 [2:42:15<39:19,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3219/4612 [2:42:17<39:31,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3220/4612 [2:42:18<39:01,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▊     | 3221/4612 [2:42:20<38:13,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3222/4612 [2:42:22<37:26,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3223/4612 [2:42:23<36:32,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3224/4612 [2:42:25<36:31,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3225/4612 [2:42:26<37:58,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3226/4612 [2:42:28<37:51,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3227/4612 [2:42:30<38:19,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3228/4612 [2:42:32<38:50,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3229/4612 [2:42:33<38:35,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3230/4612 [2:42:35<37:53,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3231/4612 [2:42:36<37:01,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3232/4612 [2:42:38<37:15,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3233/4612 [2:42:39<36:28,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3234/4612 [2:42:41<36:01,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3235/4612 [2:42:43<37:13,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3236/4612 [2:42:44<36:59,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3237/4612 [2:42:46<36:53,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3238/4612 [2:42:48<38:03,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3239/4612 [2:42:49<37:48,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3240/4612 [2:42:51<37:47,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3241/4612 [2:42:52<36:35,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3242/4612 [2:42:54<37:20,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3243/4612 [2:42:56<37:28,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3244/4612 [2:42:58<37:50,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3245/4612 [2:42:59<37:52,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3246/4612 [2:43:01<36:57,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3247/4612 [2:43:02<36:54,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3248/4612 [2:43:04<37:10,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3249/4612 [2:43:05<36:16,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3250/4612 [2:43:07<36:50,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  70%|███████████▉     | 3251/4612 [2:43:09<36:14,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|███████████▉     | 3252/4612 [2:43:10<36:19,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|███████████▉     | 3253/4612 [2:43:12<36:50,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|███████████▉     | 3254/4612 [2:43:14<36:29,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|███████████▉     | 3255/4612 [2:43:15<36:47,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3256/4612 [2:43:17<37:08,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3257/4612 [2:43:19<36:47,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3258/4612 [2:43:20<36:45,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3259/4612 [2:43:22<36:32,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3260/4612 [2:43:23<36:38,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3261/4612 [2:43:25<37:20,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3262/4612 [2:43:27<38:51,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3263/4612 [2:43:29<37:47,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3264/4612 [2:43:30<38:12,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3265/4612 [2:43:32<39:30,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3266/4612 [2:43:34<38:39,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3267/4612 [2:43:36<40:15,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3268/4612 [2:43:38<41:17,  1.84s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3269/4612 [2:43:40<42:17,  1.89s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3270/4612 [2:43:42<41:05,  1.84s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3271/4612 [2:43:43<40:27,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3272/4612 [2:43:45<39:31,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3273/4612 [2:43:47<38:08,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3274/4612 [2:43:48<37:55,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3275/4612 [2:43:50<37:30,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3276/4612 [2:43:51<37:18,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3277/4612 [2:43:53<36:34,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3278/4612 [2:43:55<36:20,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3279/4612 [2:43:56<37:27,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3280/4612 [2:43:58<38:02,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3281/4612 [2:44:01<42:03,  1.90s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3282/4612 [2:44:02<40:40,  1.84s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3283/4612 [2:44:04<38:25,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3284/4612 [2:44:05<38:22,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3285/4612 [2:44:07<38:44,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3286/4612 [2:44:09<40:10,  1.82s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3287/4612 [2:44:11<41:16,  1.87s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3288/4612 [2:44:13<38:55,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████     | 3289/4612 [2:44:14<37:41,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3290/4612 [2:44:16<37:56,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3291/4612 [2:44:18<36:59,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3292/4612 [2:44:19<37:20,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3293/4612 [2:44:21<37:31,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3294/4612 [2:44:23<37:32,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3295/4612 [2:44:24<36:57,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3296/4612 [2:44:26<36:14,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  71%|████████████▏    | 3297/4612 [2:44:28<36:14,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3298/4612 [2:44:29<35:15,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3299/4612 [2:44:31<35:44,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3300/4612 [2:44:33<35:28,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3301/4612 [2:44:34<35:51,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3302/4612 [2:44:36<36:08,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3303/4612 [2:44:37<35:21,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3304/4612 [2:44:39<35:59,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3305/4612 [2:44:41<35:38,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3306/4612 [2:44:42<35:27,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3307/4612 [2:44:44<35:36,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3308/4612 [2:44:46<35:18,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3309/4612 [2:44:47<35:38,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3310/4612 [2:44:49<36:04,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3311/4612 [2:44:51<36:43,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3312/4612 [2:44:52<35:04,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3313/4612 [2:44:54<34:59,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3314/4612 [2:44:55<33:49,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3315/4612 [2:44:57<33:29,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3316/4612 [2:44:59<34:41,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3317/4612 [2:45:00<34:24,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3318/4612 [2:45:02<34:27,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3319/4612 [2:45:03<34:32,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3320/4612 [2:45:05<34:13,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3321/4612 [2:45:07<35:26,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3322/4612 [2:45:08<36:10,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▏    | 3323/4612 [2:45:10<36:28,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3324/4612 [2:45:12<37:13,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3325/4612 [2:45:14<36:18,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3326/4612 [2:45:15<35:22,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3327/4612 [2:45:17<37:10,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3328/4612 [2:45:19<36:40,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3329/4612 [2:45:20<36:33,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3330/4612 [2:45:22<36:25,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3331/4612 [2:45:24<36:12,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3332/4612 [2:45:26<36:23,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3333/4612 [2:45:27<36:41,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3334/4612 [2:45:30<39:54,  1.87s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3335/4612 [2:45:31<40:06,  1.88s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3336/4612 [2:45:33<38:43,  1.82s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3337/4612 [2:45:35<38:27,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3338/4612 [2:45:37<37:33,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3339/4612 [2:45:38<38:06,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3340/4612 [2:45:40<38:27,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3341/4612 [2:45:42<37:24,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3342/4612 [2:45:44<36:43,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  72%|████████████▎    | 3343/4612 [2:45:45<35:56,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3344/4612 [2:45:47<34:31,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3345/4612 [2:45:48<33:34,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3346/4612 [2:45:50<33:29,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3347/4612 [2:45:51<34:25,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3348/4612 [2:45:53<35:01,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3349/4612 [2:45:55<34:59,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3350/4612 [2:45:56<34:29,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3351/4612 [2:45:58<34:53,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3352/4612 [2:46:00<35:01,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3353/4612 [2:46:02<35:40,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3354/4612 [2:46:03<35:14,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3355/4612 [2:46:05<34:48,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3356/4612 [2:46:06<34:04,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▎    | 3357/4612 [2:46:08<33:40,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3358/4612 [2:46:10<34:29,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3359/4612 [2:46:11<34:39,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3360/4612 [2:46:13<33:38,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3361/4612 [2:46:15<33:21,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3362/4612 [2:46:16<32:56,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3363/4612 [2:46:18<33:02,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3364/4612 [2:46:19<33:41,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3365/4612 [2:46:21<33:34,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3366/4612 [2:46:23<33:42,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3367/4612 [2:46:24<34:04,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3368/4612 [2:46:26<33:59,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3369/4612 [2:46:28<34:39,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3370/4612 [2:46:30<35:47,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3371/4612 [2:46:31<34:24,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3372/4612 [2:46:33<34:29,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3373/4612 [2:46:34<34:37,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3374/4612 [2:46:36<35:00,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3375/4612 [2:46:38<34:43,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3376/4612 [2:46:39<34:26,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3377/4612 [2:46:41<33:34,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3378/4612 [2:46:43<33:41,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3379/4612 [2:46:44<33:08,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3380/4612 [2:46:46<32:09,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3381/4612 [2:46:47<32:06,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3382/4612 [2:46:49<32:50,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3383/4612 [2:46:50<32:07,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3384/4612 [2:46:52<32:01,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3385/4612 [2:46:54<33:03,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3386/4612 [2:46:55<32:58,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3387/4612 [2:46:57<33:52,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3388/4612 [2:46:59<33:14,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  73%|████████████▍    | 3389/4612 [2:47:00<32:41,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▍    | 3390/4612 [2:47:02<32:33,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▍    | 3391/4612 [2:47:04<33:42,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3392/4612 [2:47:05<33:21,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3393/4612 [2:47:07<32:53,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3394/4612 [2:47:08<32:57,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3395/4612 [2:47:10<32:36,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3396/4612 [2:47:12<32:39,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3397/4612 [2:47:13<31:54,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3398/4612 [2:47:15<31:49,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3399/4612 [2:47:16<31:49,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3400/4612 [2:47:18<31:59,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3401/4612 [2:47:19<32:32,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3402/4612 [2:47:21<32:10,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3403/4612 [2:47:23<32:32,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3404/4612 [2:47:24<31:51,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3405/4612 [2:47:26<31:46,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3406/4612 [2:47:27<31:36,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3407/4612 [2:47:29<31:28,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3408/4612 [2:47:31<32:05,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3409/4612 [2:47:32<32:23,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3410/4612 [2:47:34<32:43,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3411/4612 [2:47:35<32:27,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3412/4612 [2:47:37<33:02,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3413/4612 [2:47:39<32:13,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3414/4612 [2:47:40<32:48,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3415/4612 [2:47:42<32:40,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3416/4612 [2:47:44<32:21,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3417/4612 [2:47:45<32:52,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3418/4612 [2:47:47<34:12,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3419/4612 [2:47:49<33:25,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3420/4612 [2:47:50<32:14,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3421/4612 [2:47:52<31:42,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3422/4612 [2:47:53<31:38,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3423/4612 [2:47:55<31:55,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3424/4612 [2:47:57<32:30,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▌    | 3425/4612 [2:47:58<32:33,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3426/4612 [2:48:00<33:00,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3427/4612 [2:48:02<33:11,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3428/4612 [2:48:03<32:29,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3429/4612 [2:48:05<32:37,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3430/4612 [2:48:07<32:24,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3431/4612 [2:48:08<32:54,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3432/4612 [2:48:10<32:44,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3433/4612 [2:48:12<32:15,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3434/4612 [2:48:13<31:14,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  74%|████████████▋    | 3435/4612 [2:48:15<31:52,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3436/4612 [2:48:16<31:35,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3437/4612 [2:48:18<31:13,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3438/4612 [2:48:19<30:30,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3439/4612 [2:48:21<31:01,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3440/4612 [2:48:23<31:34,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3441/4612 [2:48:25<32:20,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3442/4612 [2:48:26<32:02,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3443/4612 [2:48:28<32:20,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3444/4612 [2:48:29<31:18,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3445/4612 [2:48:31<32:25,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3446/4612 [2:48:33<33:19,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3447/4612 [2:48:35<32:44,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3448/4612 [2:48:36<32:22,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3449/4612 [2:48:38<32:20,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3450/4612 [2:48:40<32:07,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3451/4612 [2:48:41<32:34,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3452/4612 [2:48:43<32:15,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3453/4612 [2:48:45<32:48,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3454/4612 [2:48:46<31:20,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3455/4612 [2:48:48<31:11,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3456/4612 [2:48:50<32:15,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3457/4612 [2:48:51<31:51,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▋    | 3458/4612 [2:48:53<31:36,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3459/4612 [2:48:54<30:45,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3460/4612 [2:48:56<30:39,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3461/4612 [2:48:58<31:34,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3462/4612 [2:48:59<31:08,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3463/4612 [2:49:01<31:28,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3464/4612 [2:49:03<31:46,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3465/4612 [2:49:04<31:51,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3466/4612 [2:49:06<31:25,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3467/4612 [2:49:08<31:49,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3468/4612 [2:49:09<31:35,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3469/4612 [2:49:11<30:52,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3470/4612 [2:49:12<30:41,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3471/4612 [2:49:14<32:12,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3472/4612 [2:49:16<31:48,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3473/4612 [2:49:17<30:59,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3474/4612 [2:49:19<31:27,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3475/4612 [2:49:21<30:36,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3476/4612 [2:49:22<30:37,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3477/4612 [2:49:24<30:26,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3478/4612 [2:49:26<31:34,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3479/4612 [2:49:27<32:08,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3480/4612 [2:49:29<32:51,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3481/4612 [2:49:31<32:59,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  75%|████████████▊    | 3482/4612 [2:49:33<32:47,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3483/4612 [2:49:35<32:52,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3484/4612 [2:49:36<33:43,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3485/4612 [2:49:38<34:32,  1.84s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3486/4612 [2:49:40<33:54,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3487/4612 [2:49:42<33:20,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3488/4612 [2:49:43<31:40,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3489/4612 [2:49:45<31:13,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3490/4612 [2:49:47<31:16,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3491/4612 [2:49:48<31:01,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▊    | 3492/4612 [2:49:50<30:12,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3493/4612 [2:49:51<30:16,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3494/4612 [2:49:53<30:15,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3495/4612 [2:49:55<30:59,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3496/4612 [2:49:56<30:22,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3497/4612 [2:49:58<30:05,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3498/4612 [2:50:00<31:01,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3499/4612 [2:50:02<31:40,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3500/4612 [2:50:03<31:16,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3501/4612 [2:50:05<31:21,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3502/4612 [2:50:06<30:27,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3503/4612 [2:50:08<29:50,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3504/4612 [2:50:10<29:51,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3505/4612 [2:50:11<29:11,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3506/4612 [2:50:13<30:02,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3507/4612 [2:50:15<30:37,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3508/4612 [2:50:16<29:50,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3509/4612 [2:50:18<29:33,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3510/4612 [2:50:19<29:25,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3511/4612 [2:50:21<30:09,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3512/4612 [2:50:23<29:35,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3513/4612 [2:50:24<29:22,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3514/4612 [2:50:26<28:58,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3515/4612 [2:50:27<29:20,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3516/4612 [2:50:29<29:04,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3517/4612 [2:50:30<28:22,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3518/4612 [2:50:32<28:53,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3519/4612 [2:50:34<28:56,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3520/4612 [2:50:35<29:40,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3521/4612 [2:50:37<30:40,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3522/4612 [2:50:39<31:34,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3523/4612 [2:50:41<31:49,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3524/4612 [2:50:42<31:18,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3525/4612 [2:50:44<30:19,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|████████████▉    | 3526/4612 [2:50:45<29:05,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|█████████████    | 3527/4612 [2:50:47<29:02,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  76%|█████████████    | 3528/4612 [2:50:49<29:11,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3529/4612 [2:50:50<28:53,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3530/4612 [2:50:52<29:02,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3531/4612 [2:50:53<28:38,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3532/4612 [2:50:55<29:23,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3533/4612 [2:50:57<28:52,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3534/4612 [2:50:58<28:01,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3535/4612 [2:51:00<28:39,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3536/4612 [2:51:01<28:05,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3537/4612 [2:51:03<28:10,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3538/4612 [2:51:05<29:04,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3539/4612 [2:51:06<28:46,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3540/4612 [2:51:08<28:21,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3541/4612 [2:51:09<28:09,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3542/4612 [2:51:11<27:47,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3543/4612 [2:51:12<27:17,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3544/4612 [2:51:14<28:06,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3545/4612 [2:51:16<28:11,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3546/4612 [2:51:17<27:58,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3547/4612 [2:51:19<27:53,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3548/4612 [2:51:20<28:50,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3549/4612 [2:51:22<28:42,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3550/4612 [2:51:24<29:19,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3551/4612 [2:51:25<29:09,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3552/4612 [2:51:27<29:37,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3553/4612 [2:51:29<28:55,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3554/4612 [2:51:30<28:34,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3555/4612 [2:51:32<27:46,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3556/4612 [2:51:33<27:52,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3557/4612 [2:51:35<28:23,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3558/4612 [2:51:37<28:35,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3559/4612 [2:51:38<29:20,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████    | 3560/4612 [2:51:40<29:09,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3561/4612 [2:51:42<28:48,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3562/4612 [2:51:43<28:03,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3563/4612 [2:51:45<27:40,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3564/4612 [2:51:46<28:06,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3565/4612 [2:51:48<28:21,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3566/4612 [2:51:50<28:43,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3567/4612 [2:51:51<28:36,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3568/4612 [2:51:53<28:48,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3569/4612 [2:51:55<29:29,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3570/4612 [2:51:56<28:39,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3571/4612 [2:51:58<28:57,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3572/4612 [2:52:00<29:33,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3573/4612 [2:52:02<28:54,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  77%|█████████████▏   | 3574/4612 [2:52:03<28:27,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3575/4612 [2:52:05<28:38,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3576/4612 [2:52:06<28:21,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3577/4612 [2:52:08<28:24,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3578/4612 [2:52:10<27:39,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3579/4612 [2:52:11<27:12,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3580/4612 [2:52:13<28:42,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3581/4612 [2:52:14<27:48,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3582/4612 [2:52:16<27:40,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3583/4612 [2:52:18<28:36,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3584/4612 [2:52:20<29:01,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3585/4612 [2:52:21<29:13,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3586/4612 [2:52:23<28:54,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3587/4612 [2:52:25<28:03,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3588/4612 [2:52:26<27:50,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3589/4612 [2:52:28<27:33,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3590/4612 [2:52:29<27:03,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3591/4612 [2:52:31<26:45,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3592/4612 [2:52:32<26:22,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3593/4612 [2:52:34<27:25,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▏   | 3594/4612 [2:52:36<27:14,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3595/4612 [2:52:37<27:31,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3596/4612 [2:52:39<27:25,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3597/4612 [2:52:41<27:48,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3598/4612 [2:52:42<28:47,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3599/4612 [2:52:44<27:52,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3600/4612 [2:52:46<27:43,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3601/4612 [2:52:47<27:08,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3602/4612 [2:52:49<27:07,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3603/4612 [2:52:50<26:55,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3604/4612 [2:52:52<27:13,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3605/4612 [2:52:54<28:30,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3606/4612 [2:52:56<31:48,  1.90s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3607/4612 [2:52:58<30:40,  1.83s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3608/4612 [2:53:00<30:43,  1.84s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3609/4612 [2:53:02<30:09,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3610/4612 [2:53:03<29:47,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3611/4612 [2:53:05<29:33,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3612/4612 [2:53:07<28:38,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3613/4612 [2:53:08<28:44,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3614/4612 [2:53:10<28:34,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3615/4612 [2:53:12<28:47,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3616/4612 [2:53:13<27:20,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3617/4612 [2:53:15<26:28,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3618/4612 [2:53:16<26:27,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3619/4612 [2:53:18<27:20,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  78%|█████████████▎   | 3620/4612 [2:53:20<27:50,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3621/4612 [2:53:21<27:02,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3622/4612 [2:53:23<26:50,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3623/4612 [2:53:25<26:43,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3624/4612 [2:53:26<27:00,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3625/4612 [2:53:28<27:20,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3626/4612 [2:53:30<27:59,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3627/4612 [2:53:31<26:51,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▎   | 3628/4612 [2:53:33<26:34,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3629/4612 [2:53:35<26:42,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3630/4612 [2:53:36<26:07,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3631/4612 [2:53:37<25:25,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3632/4612 [2:53:39<25:40,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3633/4612 [2:53:41<25:15,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3634/4612 [2:53:42<24:52,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3635/4612 [2:53:43<24:17,  1.49s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3636/4612 [2:53:45<24:52,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3637/4612 [2:53:47<24:56,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3638/4612 [2:53:48<25:05,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3639/4612 [2:53:50<25:04,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3640/4612 [2:53:52<25:56,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3641/4612 [2:53:53<25:20,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3642/4612 [2:53:55<25:07,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3643/4612 [2:53:56<25:08,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3644/4612 [2:53:58<25:06,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3645/4612 [2:53:59<25:47,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3646/4612 [2:54:01<25:46,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3647/4612 [2:54:02<25:27,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3648/4612 [2:54:04<25:29,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3649/4612 [2:54:06<25:46,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3650/4612 [2:54:07<25:11,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3651/4612 [2:54:09<25:26,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3652/4612 [2:54:10<25:16,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3653/4612 [2:54:12<25:02,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3654/4612 [2:54:14<26:20,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3655/4612 [2:54:15<25:27,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3656/4612 [2:54:17<25:09,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3657/4612 [2:54:18<25:12,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3658/4612 [2:54:20<26:12,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3659/4612 [2:54:22<26:27,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3660/4612 [2:54:24<26:24,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3661/4612 [2:54:25<25:54,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▍   | 3662/4612 [2:54:27<25:27,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▌   | 3663/4612 [2:54:28<25:27,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▌   | 3664/4612 [2:54:30<25:43,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▌   | 3665/4612 [2:54:32<25:45,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  79%|█████████████▌   | 3666/4612 [2:54:33<25:39,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3667/4612 [2:54:35<26:16,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3668/4612 [2:54:37<26:15,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3669/4612 [2:54:38<26:15,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3670/4612 [2:54:40<26:28,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3671/4612 [2:54:42<25:47,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3672/4612 [2:54:43<25:28,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3673/4612 [2:54:45<25:43,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3674/4612 [2:54:46<25:08,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3675/4612 [2:54:48<25:44,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3676/4612 [2:54:50<26:17,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3677/4612 [2:54:51<25:31,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3678/4612 [2:54:53<25:04,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3679/4612 [2:54:55<25:27,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3680/4612 [2:54:56<25:11,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3681/4612 [2:54:58<25:00,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3682/4612 [2:54:59<24:49,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3683/4612 [2:55:01<24:41,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3684/4612 [2:55:03<24:47,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3685/4612 [2:55:04<25:23,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3686/4612 [2:55:06<25:20,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3687/4612 [2:55:08<26:43,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3688/4612 [2:55:10<26:58,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3689/4612 [2:55:11<26:04,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3690/4612 [2:55:13<25:54,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3691/4612 [2:55:14<24:45,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3692/4612 [2:55:16<24:09,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3693/4612 [2:55:18<24:24,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3694/4612 [2:55:19<24:37,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3695/4612 [2:55:21<24:42,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▌   | 3696/4612 [2:55:22<24:24,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3697/4612 [2:55:24<24:09,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3698/4612 [2:55:25<23:54,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3699/4612 [2:55:27<24:17,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3700/4612 [2:55:29<24:43,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3701/4612 [2:55:30<24:54,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3702/4612 [2:55:32<24:33,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3703/4612 [2:55:34<24:20,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3704/4612 [2:55:35<23:57,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3705/4612 [2:55:37<24:51,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3706/4612 [2:55:39<25:13,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3707/4612 [2:55:40<25:32,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3708/4612 [2:55:42<25:05,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3709/4612 [2:55:44<25:44,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3710/4612 [2:55:46<25:40,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3711/4612 [2:55:47<24:51,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  80%|█████████████▋   | 3712/4612 [2:55:49<25:23,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3713/4612 [2:55:50<24:53,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3714/4612 [2:55:52<24:39,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3715/4612 [2:55:53<23:42,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3716/4612 [2:55:55<23:59,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3717/4612 [2:55:57<23:33,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3718/4612 [2:55:58<23:40,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3719/4612 [2:56:00<23:57,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3720/4612 [2:56:02<23:44,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3721/4612 [2:56:03<24:17,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3722/4612 [2:56:05<23:35,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3723/4612 [2:56:06<23:11,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3724/4612 [2:56:08<23:54,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3725/4612 [2:56:10<26:05,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3726/4612 [2:56:12<26:20,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3727/4612 [2:56:14<26:27,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3728/4612 [2:56:15<25:28,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3729/4612 [2:56:17<26:20,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▋   | 3730/4612 [2:56:19<26:11,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3731/4612 [2:56:21<25:47,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3732/4612 [2:56:23<27:40,  1.89s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3733/4612 [2:56:24<26:20,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3734/4612 [2:56:26<25:55,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3735/4612 [2:56:28<24:51,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3736/4612 [2:56:29<24:15,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3737/4612 [2:56:31<23:50,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3738/4612 [2:56:32<23:32,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3739/4612 [2:56:34<23:44,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3740/4612 [2:56:36<23:49,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3741/4612 [2:56:37<23:51,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3742/4612 [2:56:39<23:57,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3743/4612 [2:56:41<23:44,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3744/4612 [2:56:42<23:23,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3745/4612 [2:56:44<22:55,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3746/4612 [2:56:45<22:47,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3747/4612 [2:56:47<22:47,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3748/4612 [2:56:49<23:01,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3749/4612 [2:56:50<22:07,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3750/4612 [2:56:52<22:34,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3751/4612 [2:56:53<23:10,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3752/4612 [2:56:55<22:25,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3753/4612 [2:56:56<22:16,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3754/4612 [2:56:58<22:20,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3755/4612 [2:57:00<22:39,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3756/4612 [2:57:01<23:30,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3757/4612 [2:57:03<24:22,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  81%|█████████████▊   | 3758/4612 [2:57:05<25:10,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▊   | 3759/4612 [2:57:07<25:56,  1.82s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▊   | 3760/4612 [2:57:09<25:23,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▊   | 3761/4612 [2:57:10<24:50,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▊   | 3762/4612 [2:57:12<25:09,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▊   | 3763/4612 [2:57:14<24:42,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▊   | 3764/4612 [2:57:16<24:05,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3765/4612 [2:57:17<23:41,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3766/4612 [2:57:19<22:57,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3767/4612 [2:57:20<22:46,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3768/4612 [2:57:22<22:13,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3769/4612 [2:57:23<22:01,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3770/4612 [2:57:25<21:39,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3771/4612 [2:57:26<21:29,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3772/4612 [2:57:28<21:46,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3773/4612 [2:57:29<21:26,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3774/4612 [2:57:31<22:04,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3775/4612 [2:57:33<22:36,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3776/4612 [2:57:34<22:47,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3777/4612 [2:57:36<23:04,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3778/4612 [2:57:38<22:27,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3779/4612 [2:57:39<21:42,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3780/4612 [2:57:41<22:02,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3781/4612 [2:57:42<21:49,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3782/4612 [2:57:44<22:01,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3783/4612 [2:57:46<22:33,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3784/4612 [2:57:47<21:52,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3785/4612 [2:57:49<22:16,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3786/4612 [2:57:50<22:02,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3787/4612 [2:57:52<21:40,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3788/4612 [2:57:53<21:29,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3789/4612 [2:57:55<21:31,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3790/4612 [2:57:57<21:30,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3791/4612 [2:57:59<23:56,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3792/4612 [2:58:00<22:54,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3793/4612 [2:58:02<22:03,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3794/4612 [2:58:03<21:53,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3795/4612 [2:58:05<21:32,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3796/4612 [2:58:07<22:02,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3797/4612 [2:58:08<22:07,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|█████████████▉   | 3798/4612 [2:58:10<23:09,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|██████████████   | 3799/4612 [2:58:12<23:12,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|██████████████   | 3800/4612 [2:58:14<23:09,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|██████████████   | 3801/4612 [2:58:15<22:29,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|██████████████   | 3802/4612 [2:58:17<22:16,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|██████████████   | 3803/4612 [2:58:19<23:38,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  82%|██████████████   | 3804/4612 [2:58:20<23:05,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3805/4612 [2:58:22<21:51,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3806/4612 [2:58:23<21:32,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3807/4612 [2:58:25<21:40,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3808/4612 [2:58:27<21:36,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3809/4612 [2:58:28<21:33,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3810/4612 [2:58:30<21:09,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3811/4612 [2:58:31<20:46,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3812/4612 [2:58:33<20:24,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3813/4612 [2:58:34<20:57,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3814/4612 [2:58:36<22:01,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3815/4612 [2:58:38<21:34,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3816/4612 [2:58:39<21:09,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3817/4612 [2:58:41<20:58,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3818/4612 [2:58:42<21:12,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3819/4612 [2:58:44<21:21,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3820/4612 [2:58:46<21:54,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3821/4612 [2:58:47<21:49,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3822/4612 [2:58:49<22:09,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3823/4612 [2:58:51<21:24,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3824/4612 [2:58:52<21:37,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3825/4612 [2:58:54<21:09,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3826/4612 [2:58:55<20:39,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3827/4612 [2:58:57<20:07,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3828/4612 [2:58:59<21:07,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3829/4612 [2:59:00<20:53,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3830/4612 [2:59:02<20:21,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3831/4612 [2:59:03<20:41,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████   | 3832/4612 [2:59:05<20:22,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3833/4612 [2:59:06<20:28,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3834/4612 [2:59:08<20:39,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3835/4612 [2:59:10<21:16,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3836/4612 [2:59:11<20:53,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3837/4612 [2:59:13<21:03,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3838/4612 [2:59:15<21:16,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3839/4612 [2:59:17<22:09,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3840/4612 [2:59:18<21:50,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3841/4612 [2:59:20<22:02,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3842/4612 [2:59:22<22:17,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3843/4612 [2:59:24<22:33,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3844/4612 [2:59:25<22:09,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3845/4612 [2:59:27<21:58,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3846/4612 [2:59:29<22:03,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3847/4612 [2:59:30<21:32,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3848/4612 [2:59:32<21:22,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3849/4612 [2:59:34<21:22,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3850/4612 [2:59:35<21:26,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  83%|██████████████▏  | 3851/4612 [2:59:37<21:06,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3852/4612 [2:59:39<20:57,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3853/4612 [2:59:40<21:12,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3854/4612 [2:59:42<20:35,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3855/4612 [2:59:43<20:10,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3856/4612 [2:59:45<20:14,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3857/4612 [2:59:47<20:18,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3858/4612 [2:59:48<20:36,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3859/4612 [2:59:50<20:43,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3860/4612 [2:59:52<20:45,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3861/4612 [2:59:53<20:45,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3862/4612 [2:59:55<20:55,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3863/4612 [2:59:57<20:47,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3864/4612 [2:59:59<21:03,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▏  | 3865/4612 [3:00:00<21:17,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3866/4612 [3:00:02<20:45,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3867/4612 [3:00:03<20:21,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3868/4612 [3:00:05<20:04,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3869/4612 [3:00:07<19:50,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3870/4612 [3:00:08<20:33,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3871/4612 [3:00:10<21:23,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3872/4612 [3:00:12<21:00,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3873/4612 [3:00:14<20:44,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3874/4612 [3:00:15<21:00,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3875/4612 [3:00:17<21:00,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3876/4612 [3:00:19<20:14,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3877/4612 [3:00:20<19:46,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3878/4612 [3:00:21<19:06,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3879/4612 [3:00:23<19:43,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3880/4612 [3:00:25<19:56,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3881/4612 [3:00:26<19:44,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3882/4612 [3:00:28<19:32,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3883/4612 [3:00:30<19:37,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3884/4612 [3:00:31<19:05,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3885/4612 [3:00:33<20:05,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3886/4612 [3:00:35<20:23,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3887/4612 [3:00:36<19:43,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3888/4612 [3:00:38<19:48,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3889/4612 [3:00:40<20:13,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3890/4612 [3:00:41<19:40,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3891/4612 [3:00:43<19:54,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3892/4612 [3:00:45<19:42,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3893/4612 [3:00:46<19:16,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3894/4612 [3:00:48<19:43,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3895/4612 [3:00:49<19:33,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3896/4612 [3:00:51<19:46,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  84%|██████████████▎  | 3897/4612 [3:00:53<20:19,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▎  | 3898/4612 [3:00:55<21:00,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▎  | 3899/4612 [3:00:57<21:10,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3900/4612 [3:00:58<20:26,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3901/4612 [3:01:00<20:42,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3902/4612 [3:01:02<20:35,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3903/4612 [3:01:04<20:58,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3904/4612 [3:01:06<21:39,  1.83s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3905/4612 [3:01:08<22:00,  1.87s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3906/4612 [3:01:09<21:44,  1.85s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3907/4612 [3:01:11<20:58,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3908/4612 [3:01:13<20:41,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3909/4612 [3:01:14<20:32,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3910/4612 [3:01:16<19:57,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3911/4612 [3:01:18<19:41,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3912/4612 [3:01:19<19:30,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3913/4612 [3:01:21<19:14,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3914/4612 [3:01:23<19:18,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3915/4612 [3:01:24<19:34,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3916/4612 [3:01:26<19:18,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3917/4612 [3:01:28<19:44,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3918/4612 [3:01:29<18:59,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3919/4612 [3:01:31<19:06,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3920/4612 [3:01:33<18:56,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3921/4612 [3:01:34<19:14,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3922/4612 [3:01:36<19:12,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3923/4612 [3:01:38<18:46,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3924/4612 [3:01:39<19:05,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3925/4612 [3:01:41<18:43,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3926/4612 [3:01:42<18:38,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3927/4612 [3:01:44<18:44,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3928/4612 [3:01:46<19:00,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3929/4612 [3:01:47<18:52,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3930/4612 [3:01:49<18:27,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3931/4612 [3:01:51<18:08,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3932/4612 [3:01:52<18:28,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▍  | 3933/4612 [3:01:54<18:26,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3934/4612 [3:01:56<18:31,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3935/4612 [3:01:57<18:36,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3936/4612 [3:01:59<18:22,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3937/4612 [3:02:00<18:14,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3938/4612 [3:02:02<18:18,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3939/4612 [3:02:04<18:12,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3940/4612 [3:02:05<18:40,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3941/4612 [3:02:07<19:07,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3942/4612 [3:02:09<19:43,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  85%|██████████████▌  | 3943/4612 [3:02:11<18:55,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3944/4612 [3:02:12<18:31,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3945/4612 [3:02:14<18:31,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3946/4612 [3:02:16<18:35,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3947/4612 [3:02:17<18:38,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3948/4612 [3:02:19<19:22,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3949/4612 [3:02:21<18:41,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3950/4612 [3:02:22<18:10,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3951/4612 [3:02:24<18:03,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3952/4612 [3:02:26<19:21,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3953/4612 [3:02:28<19:32,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3954/4612 [3:02:29<18:53,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3955/4612 [3:02:31<18:50,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3956/4612 [3:02:33<19:02,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3957/4612 [3:02:35<18:45,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3958/4612 [3:02:36<18:32,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3959/4612 [3:02:38<18:51,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3960/4612 [3:02:40<19:30,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3961/4612 [3:02:42<20:28,  1.89s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3962/4612 [3:02:44<20:40,  1.91s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3963/4612 [3:02:46<19:33,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3964/4612 [3:02:47<19:04,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3965/4612 [3:02:49<19:02,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3966/4612 [3:02:51<18:46,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▌  | 3967/4612 [3:02:53<18:48,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3968/4612 [3:02:54<19:14,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3969/4612 [3:02:56<19:03,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3970/4612 [3:02:58<18:52,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3971/4612 [3:03:00<19:07,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3972/4612 [3:03:02<19:08,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3973/4612 [3:03:03<18:17,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3974/4612 [3:03:05<18:09,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3975/4612 [3:03:06<17:36,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3976/4612 [3:03:08<17:39,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3977/4612 [3:03:10<17:46,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3978/4612 [3:03:11<17:11,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3979/4612 [3:03:13<16:52,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3980/4612 [3:03:14<16:29,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3981/4612 [3:03:16<16:55,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3982/4612 [3:03:18<16:59,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3983/4612 [3:03:19<17:08,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3984/4612 [3:03:21<17:31,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3985/4612 [3:03:22<16:48,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3986/4612 [3:03:24<16:41,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3987/4612 [3:03:26<16:49,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3988/4612 [3:03:27<17:12,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  86%|██████████████▋  | 3989/4612 [3:03:29<17:07,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3990/4612 [3:03:31<16:52,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3991/4612 [3:03:32<17:03,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3992/4612 [3:03:34<16:52,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3993/4612 [3:03:36<16:50,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3994/4612 [3:03:37<16:23,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3995/4612 [3:03:39<16:23,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3996/4612 [3:03:40<16:25,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3997/4612 [3:03:42<17:04,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3998/4612 [3:03:44<16:41,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 3999/4612 [3:03:45<16:47,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 4000/4612 [3:03:47<16:49,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▋  | 4001/4612 [3:03:49<16:48,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4002/4612 [3:03:50<16:36,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4003/4612 [3:03:52<16:15,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4004/4612 [3:03:53<16:20,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4005/4612 [3:03:55<16:41,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4006/4612 [3:03:57<17:00,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4007/4612 [3:03:59<17:32,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4008/4612 [3:04:01<17:56,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4009/4612 [3:04:02<17:26,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4010/4612 [3:04:04<17:29,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4011/4612 [3:04:06<17:01,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4012/4612 [3:04:07<16:29,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4013/4612 [3:04:09<17:02,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4014/4612 [3:04:11<17:36,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4015/4612 [3:04:13<17:29,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4016/4612 [3:04:14<16:55,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4017/4612 [3:04:16<16:59,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4018/4612 [3:04:17<16:21,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4019/4612 [3:04:19<16:22,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4020/4612 [3:04:21<16:38,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4021/4612 [3:04:23<16:19,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4022/4612 [3:04:24<16:31,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4023/4612 [3:04:26<15:58,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4024/4612 [3:04:27<15:45,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4025/4612 [3:04:29<15:43,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4026/4612 [3:04:31<15:54,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4027/4612 [3:04:32<15:54,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4028/4612 [3:04:34<15:56,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4029/4612 [3:04:36<16:09,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4030/4612 [3:04:37<15:56,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4031/4612 [3:04:39<16:10,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4032/4612 [3:04:41<15:57,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4033/4612 [3:04:42<16:05,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4034/4612 [3:04:44<16:06,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  87%|██████████████▊  | 4035/4612 [3:04:45<15:39,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4036/4612 [3:04:47<16:03,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4037/4612 [3:04:49<15:58,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4038/4612 [3:04:50<15:39,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4039/4612 [3:04:52<15:23,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4040/4612 [3:04:54<15:02,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4041/4612 [3:04:55<15:04,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4042/4612 [3:04:57<15:27,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4043/4612 [3:04:58<15:17,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4044/4612 [3:05:00<15:24,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4045/4612 [3:05:02<15:44,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4046/4612 [3:05:04<15:49,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4047/4612 [3:05:05<15:08,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4048/4612 [3:05:06<14:38,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4049/4612 [3:05:08<14:57,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4050/4612 [3:05:10<15:17,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4051/4612 [3:05:11<15:06,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4052/4612 [3:05:13<15:07,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4053/4612 [3:05:15<15:05,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4054/4612 [3:05:16<14:40,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4055/4612 [3:05:18<14:51,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4056/4612 [3:05:20<15:21,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4057/4612 [3:05:21<14:57,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4058/4612 [3:05:23<14:46,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4059/4612 [3:05:24<14:27,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4060/4612 [3:05:26<14:17,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4061/4612 [3:05:28<15:25,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4062/4612 [3:05:29<14:56,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4063/4612 [3:05:31<15:05,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4064/4612 [3:05:32<14:56,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4065/4612 [3:05:34<14:37,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4066/4612 [3:05:36<15:06,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4067/4612 [3:05:37<15:04,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4068/4612 [3:05:39<14:54,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|██████████████▉  | 4069/4612 [3:05:41<14:41,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4070/4612 [3:05:42<14:40,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4071/4612 [3:05:44<14:44,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4072/4612 [3:05:46<14:51,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4073/4612 [3:05:47<14:48,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4074/4612 [3:05:49<14:54,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4075/4612 [3:05:51<14:56,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4076/4612 [3:05:52<14:43,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4077/4612 [3:05:54<14:22,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4078/4612 [3:05:55<14:22,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4079/4612 [3:05:57<14:18,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4080/4612 [3:05:59<14:07,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  88%|███████████████  | 4081/4612 [3:06:00<14:21,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4082/4612 [3:06:02<13:48,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4083/4612 [3:06:03<14:05,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4084/4612 [3:06:05<14:08,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4085/4612 [3:06:06<13:51,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4086/4612 [3:06:08<13:55,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4087/4612 [3:06:10<13:55,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4088/4612 [3:06:11<13:52,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4089/4612 [3:06:13<13:38,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4090/4612 [3:06:14<13:53,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4091/4612 [3:06:16<14:21,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4092/4612 [3:06:18<14:11,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4093/4612 [3:06:20<14:19,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4094/4612 [3:06:21<13:57,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4095/4612 [3:06:23<13:39,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4096/4612 [3:06:24<13:48,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4097/4612 [3:06:26<13:44,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4098/4612 [3:06:27<13:43,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4099/4612 [3:06:29<13:31,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4100/4612 [3:06:30<13:05,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4101/4612 [3:06:32<13:41,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4102/4612 [3:06:34<14:06,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████  | 4103/4612 [3:06:36<14:18,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4104/4612 [3:06:37<14:21,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4105/4612 [3:06:39<14:01,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4106/4612 [3:06:41<13:49,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4107/4612 [3:06:42<14:08,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4108/4612 [3:06:44<13:53,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4109/4612 [3:06:45<13:25,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4110/4612 [3:06:47<13:28,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4111/4612 [3:06:49<13:33,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4112/4612 [3:06:50<13:18,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4113/4612 [3:06:52<13:13,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4114/4612 [3:06:53<12:59,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4115/4612 [3:06:55<12:54,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4116/4612 [3:06:56<12:49,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4117/4612 [3:06:58<13:09,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4118/4612 [3:07:00<13:08,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4119/4612 [3:07:01<13:31,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4120/4612 [3:07:03<13:03,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4121/4612 [3:07:05<13:22,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4122/4612 [3:07:06<13:07,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4123/4612 [3:07:08<13:19,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4124/4612 [3:07:10<13:16,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4125/4612 [3:07:11<13:13,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4126/4612 [3:07:13<13:14,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  89%|███████████████▏ | 4127/4612 [3:07:14<13:00,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4128/4612 [3:07:16<13:00,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4129/4612 [3:07:18<13:08,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4130/4612 [3:07:19<12:56,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4131/4612 [3:07:21<12:59,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4132/4612 [3:07:22<12:39,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4133/4612 [3:07:24<12:34,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4134/4612 [3:07:25<12:12,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4135/4612 [3:07:27<12:33,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4136/4612 [3:07:29<12:21,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▏ | 4137/4612 [3:07:30<12:17,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4138/4612 [3:07:32<12:27,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4139/4612 [3:07:33<12:49,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4140/4612 [3:07:35<12:49,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4141/4612 [3:07:37<12:23,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4142/4612 [3:07:38<12:34,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4143/4612 [3:07:40<12:12,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4144/4612 [3:07:41<12:18,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4145/4612 [3:07:43<12:29,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4146/4612 [3:07:45<12:34,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4147/4612 [3:07:46<12:52,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4148/4612 [3:07:48<12:38,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4149/4612 [3:07:49<12:18,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4150/4612 [3:07:51<12:13,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4151/4612 [3:07:53<12:28,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4152/4612 [3:07:54<12:42,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4153/4612 [3:07:56<12:25,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4154/4612 [3:07:58<12:25,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4155/4612 [3:07:59<12:18,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4156/4612 [3:08:01<12:15,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4157/4612 [3:08:02<11:57,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4158/4612 [3:08:04<11:41,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4159/4612 [3:08:05<11:39,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4160/4612 [3:08:07<11:43,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4161/4612 [3:08:08<11:48,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4162/4612 [3:08:10<12:03,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4163/4612 [3:08:12<12:10,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4164/4612 [3:08:13<12:08,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4165/4612 [3:08:15<12:10,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4166/4612 [3:08:17<12:10,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4167/4612 [3:08:19<12:54,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4168/4612 [3:08:20<12:29,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4169/4612 [3:08:22<12:42,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4170/4612 [3:08:24<12:37,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▎ | 4171/4612 [3:08:25<12:09,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▍ | 4172/4612 [3:08:27<12:13,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  90%|███████████████▍ | 4173/4612 [3:08:29<12:24,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4174/4612 [3:08:30<12:16,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4175/4612 [3:08:32<12:37,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4176/4612 [3:08:34<12:41,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4177/4612 [3:08:36<12:06,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4178/4612 [3:08:37<11:44,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4179/4612 [3:08:39<12:01,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4180/4612 [3:08:40<11:56,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4181/4612 [3:08:42<11:48,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4182/4612 [3:08:44<11:33,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4183/4612 [3:08:45<11:18,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4184/4612 [3:08:47<11:36,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4185/4612 [3:08:48<11:19,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4186/4612 [3:08:50<11:02,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4187/4612 [3:08:51<11:09,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4188/4612 [3:08:53<11:19,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4189/4612 [3:08:55<11:09,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4190/4612 [3:08:56<10:48,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4191/4612 [3:08:58<11:07,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4192/4612 [3:08:59<11:07,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4193/4612 [3:09:01<11:12,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4194/4612 [3:09:03<11:11,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4195/4612 [3:09:04<11:18,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4196/4612 [3:09:06<11:08,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4197/4612 [3:09:08<11:14,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4198/4612 [3:09:09<11:40,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4199/4612 [3:09:11<11:12,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4200/4612 [3:09:12<10:59,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4201/4612 [3:09:14<11:03,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4202/4612 [3:09:16<10:54,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4203/4612 [3:09:17<10:52,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4204/4612 [3:09:19<11:01,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▍ | 4205/4612 [3:09:21<11:07,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4206/4612 [3:09:22<11:05,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4207/4612 [3:09:24<10:51,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4208/4612 [3:09:26<11:36,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4209/4612 [3:09:28<13:30,  2.01s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4210/4612 [3:09:30<12:39,  1.89s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4211/4612 [3:09:32<12:21,  1.85s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4212/4612 [3:09:33<11:58,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4213/4612 [3:09:35<11:40,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4214/4612 [3:09:37<11:40,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4215/4612 [3:09:39<11:25,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4216/4612 [3:09:40<11:23,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4217/4612 [3:09:42<10:57,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4218/4612 [3:09:43<10:48,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  91%|███████████████▌ | 4219/4612 [3:09:45<10:54,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4220/4612 [3:09:47<10:41,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4221/4612 [3:09:49<11:22,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4222/4612 [3:09:50<11:14,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4223/4612 [3:09:52<11:22,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4224/4612 [3:09:54<11:48,  1.83s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4225/4612 [3:09:56<11:21,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4226/4612 [3:09:58<11:38,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4227/4612 [3:09:59<11:32,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4228/4612 [3:10:01<11:39,  1.82s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4229/4612 [3:10:03<11:06,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4230/4612 [3:10:05<10:49,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4231/4612 [3:10:06<10:57,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4232/4612 [3:10:08<10:37,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4233/4612 [3:10:10<10:45,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4234/4612 [3:10:11<10:40,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4235/4612 [3:10:13<10:45,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4236/4612 [3:10:15<10:41,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4237/4612 [3:10:16<10:25,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▌ | 4238/4612 [3:10:18<10:10,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4239/4612 [3:10:20<10:26,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4240/4612 [3:10:21<10:21,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4241/4612 [3:10:23<10:19,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4242/4612 [3:10:25<10:18,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4243/4612 [3:10:26<10:10,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4244/4612 [3:10:28<10:01,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4245/4612 [3:10:30<10:03,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4246/4612 [3:10:31<10:17,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4247/4612 [3:10:33<09:53,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4248/4612 [3:10:35<10:01,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4249/4612 [3:10:36<09:43,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4250/4612 [3:10:38<09:46,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4251/4612 [3:10:39<10:03,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4252/4612 [3:10:41<09:48,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4253/4612 [3:10:43<09:55,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4254/4612 [3:10:44<09:46,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4255/4612 [3:10:46<09:52,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4256/4612 [3:10:48<09:37,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4257/4612 [3:10:49<09:35,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4258/4612 [3:10:51<09:29,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4259/4612 [3:10:52<09:35,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4260/4612 [3:10:54<09:37,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4261/4612 [3:10:56<09:38,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4262/4612 [3:10:57<09:24,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4263/4612 [3:10:59<09:34,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4264/4612 [3:11:01<09:39,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4265/4612 [3:11:02<09:23,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  92%|███████████████▋ | 4266/4612 [3:11:04<09:10,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▋ | 4267/4612 [3:11:05<09:00,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▋ | 4268/4612 [3:11:07<09:09,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▋ | 4269/4612 [3:11:09<09:11,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▋ | 4270/4612 [3:11:10<09:01,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▋ | 4271/4612 [3:11:12<08:57,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▋ | 4272/4612 [3:11:13<09:00,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4273/4612 [3:11:15<09:10,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4274/4612 [3:11:17<08:57,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4275/4612 [3:11:18<08:48,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4276/4612 [3:11:20<09:00,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4277/4612 [3:11:21<08:58,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4278/4612 [3:11:23<08:48,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4279/4612 [3:11:25<08:59,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4280/4612 [3:11:26<08:58,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4281/4612 [3:11:28<08:53,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4282/4612 [3:11:29<08:56,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4283/4612 [3:11:31<08:52,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4284/4612 [3:11:33<08:56,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4285/4612 [3:11:34<09:00,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4286/4612 [3:11:36<08:58,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4287/4612 [3:11:38<08:48,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4288/4612 [3:11:39<08:41,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4289/4612 [3:11:41<08:49,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4290/4612 [3:11:42<08:40,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4291/4612 [3:11:44<08:34,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4292/4612 [3:11:46<08:29,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4293/4612 [3:11:47<08:15,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4294/4612 [3:11:49<08:10,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4295/4612 [3:11:50<07:58,  1.51s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4296/4612 [3:11:52<08:04,  1.53s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4297/4612 [3:11:53<08:20,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4298/4612 [3:11:55<08:24,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4299/4612 [3:11:57<08:20,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4300/4612 [3:11:58<08:24,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4301/4612 [3:12:00<08:15,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4302/4612 [3:12:02<08:28,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4303/4612 [3:12:03<08:25,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4304/4612 [3:12:05<08:26,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4305/4612 [3:12:06<08:25,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▊ | 4306/4612 [3:12:08<08:16,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▉ | 4307/4612 [3:12:10<08:05,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▉ | 4308/4612 [3:12:11<08:17,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▉ | 4309/4612 [3:12:13<08:16,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▉ | 4310/4612 [3:12:15<08:22,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▉ | 4311/4612 [3:12:16<08:28,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  93%|███████████████▉ | 4312/4612 [3:12:18<08:26,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4313/4612 [3:12:20<08:28,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4314/4612 [3:12:21<08:14,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4315/4612 [3:12:23<08:13,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4316/4612 [3:12:25<08:09,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4317/4612 [3:12:26<08:07,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4318/4612 [3:12:28<08:00,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4319/4612 [3:12:29<07:42,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4320/4612 [3:12:31<07:49,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4321/4612 [3:12:33<07:50,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4322/4612 [3:12:34<07:43,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4323/4612 [3:12:36<07:37,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4324/4612 [3:12:37<07:26,  1.55s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4325/4612 [3:12:39<07:20,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4326/4612 [3:12:40<07:28,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4327/4612 [3:12:42<07:36,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4328/4612 [3:12:44<07:41,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4329/4612 [3:12:45<07:49,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4330/4612 [3:12:47<07:44,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4331/4612 [3:12:49<07:47,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4332/4612 [3:12:51<07:54,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4333/4612 [3:12:52<08:08,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4334/4612 [3:12:54<07:51,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4335/4612 [3:12:56<07:45,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4336/4612 [3:12:57<07:49,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4337/4612 [3:12:59<07:39,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4338/4612 [3:13:01<07:46,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4339/4612 [3:13:02<07:32,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|███████████████▉ | 4340/4612 [3:13:04<07:29,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4341/4612 [3:13:06<07:47,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4342/4612 [3:13:07<07:34,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4343/4612 [3:13:09<07:23,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4344/4612 [3:13:11<07:41,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4345/4612 [3:13:13<07:42,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4346/4612 [3:13:14<07:29,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4347/4612 [3:13:16<07:23,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4348/4612 [3:13:18<07:14,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4349/4612 [3:13:19<07:15,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4350/4612 [3:13:21<07:17,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4351/4612 [3:13:23<07:24,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4352/4612 [3:13:24<07:23,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4353/4612 [3:13:26<07:17,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4354/4612 [3:13:28<07:20,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4355/4612 [3:13:30<07:23,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4356/4612 [3:13:31<07:20,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4357/4612 [3:13:33<07:21,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  94%|████████████████ | 4358/4612 [3:13:34<06:57,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4359/4612 [3:13:36<06:58,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4360/4612 [3:13:38<06:49,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4361/4612 [3:13:39<06:54,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4362/4612 [3:13:41<06:49,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4363/4612 [3:13:43<06:36,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4364/4612 [3:13:44<06:33,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4365/4612 [3:13:46<06:36,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4366/4612 [3:13:47<06:38,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4367/4612 [3:13:49<06:36,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4368/4612 [3:13:50<06:24,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4369/4612 [3:13:52<06:37,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4370/4612 [3:13:54<06:31,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4371/4612 [3:13:55<06:30,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4372/4612 [3:13:57<06:47,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4373/4612 [3:13:59<06:46,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████ | 4374/4612 [3:14:01<06:37,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4375/4612 [3:14:02<06:42,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4376/4612 [3:14:04<06:29,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4377/4612 [3:14:05<06:21,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4378/4612 [3:14:07<06:19,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4379/4612 [3:14:09<06:11,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4380/4612 [3:14:10<06:25,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4381/4612 [3:14:12<06:22,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4382/4612 [3:14:14<06:28,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4383/4612 [3:14:15<06:13,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4384/4612 [3:14:17<06:11,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4385/4612 [3:14:19<06:02,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4386/4612 [3:14:20<05:59,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4387/4612 [3:14:22<06:00,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4388/4612 [3:14:23<05:54,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4389/4612 [3:14:25<05:53,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4390/4612 [3:14:27<06:23,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4391/4612 [3:14:29<06:21,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4392/4612 [3:14:30<06:22,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4393/4612 [3:14:32<06:42,  1.84s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4394/4612 [3:14:34<06:29,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4395/4612 [3:14:36<06:21,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4396/4612 [3:14:38<06:26,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4397/4612 [3:14:39<06:12,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4398/4612 [3:14:41<06:12,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4399/4612 [3:14:43<05:58,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4400/4612 [3:14:44<06:00,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4401/4612 [3:14:46<05:55,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4402/4612 [3:14:48<05:52,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4403/4612 [3:14:49<05:53,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  95%|████████████████▏| 4404/4612 [3:14:51<05:52,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▏| 4405/4612 [3:14:53<05:40,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▏| 4406/4612 [3:14:54<05:27,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▏| 4407/4612 [3:14:56<05:23,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▏| 4408/4612 [3:14:57<05:34,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4409/4612 [3:14:59<05:42,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4410/4612 [3:15:01<05:28,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4411/4612 [3:15:02<05:27,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4412/4612 [3:15:04<05:46,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4413/4612 [3:15:06<05:41,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4414/4612 [3:15:08<05:34,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4415/4612 [3:15:09<05:32,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4416/4612 [3:15:11<05:24,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4417/4612 [3:15:12<05:20,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4418/4612 [3:15:14<05:19,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4419/4612 [3:15:16<05:18,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4420/4612 [3:15:17<05:16,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4421/4612 [3:15:19<05:21,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4422/4612 [3:15:21<05:13,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4423/4612 [3:15:22<05:11,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4424/4612 [3:15:24<05:15,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4425/4612 [3:15:26<05:12,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4426/4612 [3:15:28<05:12,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4427/4612 [3:15:29<05:14,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4428/4612 [3:15:31<05:01,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4429/4612 [3:15:32<04:51,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4430/4612 [3:15:34<04:47,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4431/4612 [3:15:35<04:51,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4432/4612 [3:15:37<04:52,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4433/4612 [3:15:39<04:50,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4434/4612 [3:15:40<04:46,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4435/4612 [3:15:42<04:48,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4436/4612 [3:15:44<04:46,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4437/4612 [3:15:45<04:40,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4438/4612 [3:15:47<04:56,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4439/4612 [3:15:49<04:47,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4440/4612 [3:15:50<04:48,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4441/4612 [3:15:53<05:08,  1.80s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▎| 4442/4612 [3:15:54<04:54,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4443/4612 [3:15:56<04:56,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4444/4612 [3:15:58<04:52,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4445/4612 [3:16:00<05:01,  1.81s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4446/4612 [3:16:01<04:57,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4447/4612 [3:16:03<04:43,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4448/4612 [3:16:04<04:31,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4449/4612 [3:16:06<04:26,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  96%|████████████████▍| 4450/4612 [3:16:08<04:25,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4451/4612 [3:16:09<04:20,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4452/4612 [3:16:11<04:15,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4453/4612 [3:16:12<04:16,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4454/4612 [3:16:14<04:12,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4455/4612 [3:16:16<04:16,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4456/4612 [3:16:17<04:20,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4457/4612 [3:16:19<04:12,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4458/4612 [3:16:21<04:16,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4459/4612 [3:16:22<04:07,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4460/4612 [3:16:24<04:03,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4461/4612 [3:16:25<04:00,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4462/4612 [3:16:27<04:02,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4463/4612 [3:16:29<04:02,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4464/4612 [3:16:30<03:55,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4465/4612 [3:16:32<03:56,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4466/4612 [3:16:34<04:00,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4467/4612 [3:16:35<03:57,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4468/4612 [3:16:37<03:54,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4469/4612 [3:16:38<03:52,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4470/4612 [3:16:40<03:53,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4471/4612 [3:16:42<03:46,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4472/4612 [3:16:43<03:38,  1.56s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4473/4612 [3:16:45<03:34,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4474/4612 [3:16:46<03:32,  1.54s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4475/4612 [3:16:48<03:37,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▍| 4476/4612 [3:16:49<03:39,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4477/4612 [3:16:51<03:38,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4478/4612 [3:16:53<03:38,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4479/4612 [3:16:54<03:33,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4480/4612 [3:16:56<03:34,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4481/4612 [3:16:57<03:27,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4482/4612 [3:16:59<03:32,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4483/4612 [3:17:01<03:29,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4484/4612 [3:17:02<03:26,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4485/4612 [3:17:04<03:32,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4486/4612 [3:17:06<03:22,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4487/4612 [3:17:07<03:21,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4488/4612 [3:17:09<03:19,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4489/4612 [3:17:10<03:16,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4490/4612 [3:17:12<03:15,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4491/4612 [3:17:14<03:12,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4492/4612 [3:17:15<03:11,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4493/4612 [3:17:17<03:14,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4494/4612 [3:17:19<03:10,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4495/4612 [3:17:20<03:06,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  97%|████████████████▌| 4496/4612 [3:17:22<03:11,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4497/4612 [3:17:23<03:05,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4498/4612 [3:17:25<02:59,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4499/4612 [3:17:26<02:57,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4500/4612 [3:17:28<02:55,  1.57s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4501/4612 [3:17:30<02:58,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4502/4612 [3:17:31<02:58,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4503/4612 [3:17:33<03:02,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4504/4612 [3:17:35<02:55,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4505/4612 [3:17:36<02:53,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4506/4612 [3:17:38<02:49,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4507/4612 [3:17:39<02:49,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4508/4612 [3:17:41<02:48,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4509/4612 [3:17:43<02:46,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▌| 4510/4612 [3:17:44<02:48,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4511/4612 [3:17:46<02:46,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4512/4612 [3:17:48<02:42,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4513/4612 [3:17:49<02:42,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4514/4612 [3:17:51<02:40,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4515/4612 [3:17:53<02:36,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4516/4612 [3:17:54<02:35,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4517/4612 [3:17:56<02:36,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4518/4612 [3:17:58<02:37,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4519/4612 [3:17:59<02:32,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4520/4612 [3:18:01<02:33,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4521/4612 [3:18:02<02:28,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4522/4612 [3:18:04<02:23,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4523/4612 [3:18:06<02:24,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4524/4612 [3:18:07<02:23,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4525/4612 [3:18:09<02:20,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4526/4612 [3:18:10<02:16,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4527/4612 [3:18:12<02:16,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4528/4612 [3:18:14<02:15,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4529/4612 [3:18:16<02:22,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4530/4612 [3:18:17<02:23,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4531/4612 [3:18:19<02:17,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4532/4612 [3:18:21<02:19,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4533/4612 [3:18:23<02:18,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4534/4612 [3:18:24<02:17,  1.77s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4535/4612 [3:18:26<02:16,  1.78s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4536/4612 [3:18:28<02:10,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4537/4612 [3:18:29<02:04,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4538/4612 [3:18:31<02:02,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4539/4612 [3:18:32<01:57,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4540/4612 [3:18:34<01:57,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4541/4612 [3:18:36<01:54,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  98%|████████████████▋| 4542/4612 [3:18:37<01:54,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▋| 4543/4612 [3:18:39<02:01,  1.76s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▋| 4544/4612 [3:18:41<01:58,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4545/4612 [3:18:43<01:55,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4546/4612 [3:18:45<01:54,  1.73s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4547/4612 [3:18:46<01:56,  1.79s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4548/4612 [3:18:48<01:51,  1.75s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4549/4612 [3:18:50<01:46,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4550/4612 [3:18:51<01:43,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4551/4612 [3:18:53<01:42,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4552/4612 [3:18:55<01:42,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4553/4612 [3:18:57<01:42,  1.74s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4554/4612 [3:18:58<01:39,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4555/4612 [3:19:00<01:35,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4556/4612 [3:19:01<01:32,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4557/4612 [3:19:03<01:27,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4558/4612 [3:19:04<01:25,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4559/4612 [3:19:06<01:23,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4560/4612 [3:19:08<01:23,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4561/4612 [3:19:09<01:21,  1.59s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4562/4612 [3:19:11<01:20,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4563/4612 [3:19:13<01:21,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4564/4612 [3:19:14<01:18,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4565/4612 [3:19:16<01:16,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4566/4612 [3:19:18<01:18,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4567/4612 [3:19:19<01:16,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4568/4612 [3:19:21<01:12,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4569/4612 [3:19:23<01:10,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4570/4612 [3:19:24<01:07,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4571/4612 [3:19:26<01:08,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4572/4612 [3:19:28<01:07,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4573/4612 [3:19:29<01:07,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4574/4612 [3:19:31<01:05,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4575/4612 [3:19:33<01:02,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4576/4612 [3:19:35<01:00,  1.69s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4577/4612 [3:19:36<01:00,  1.72s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▊| 4578/4612 [3:19:38<00:57,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4579/4612 [3:19:39<00:53,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4580/4612 [3:19:41<00:50,  1.58s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4581/4612 [3:19:43<00:50,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4582/4612 [3:19:44<00:50,  1.68s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4583/4612 [3:19:46<00:47,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4584/4612 [3:19:48<00:46,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4585/4612 [3:19:49<00:44,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4586/4612 [3:19:51<00:41,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4587/4612 [3:19:52<00:40,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches:  99%|████████████████▉| 4588/4612 [3:19:54<00:38,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4589/4612 [3:19:56<00:37,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4590/4612 [3:19:57<00:35,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4591/4612 [3:19:59<00:34,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4592/4612 [3:20:01<00:32,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4593/4612 [3:20:02<00:31,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4594/4612 [3:20:04<00:29,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4595/4612 [3:20:05<00:27,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4596/4612 [3:20:07<00:25,  1.62s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4597/4612 [3:20:09<00:24,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4598/4612 [3:20:11<00:23,  1.70s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4599/4612 [3:20:12<00:21,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4600/4612 [3:20:14<00:19,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4601/4612 [3:20:15<00:17,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4602/4612 [3:20:17<00:16,  1.64s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4603/4612 [3:20:19<00:14,  1.65s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4604/4612 [3:20:20<00:13,  1.67s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4605/4612 [3:20:22<00:11,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4606/4612 [3:20:24<00:09,  1.66s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4607/4612 [3:20:25<00:08,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4608/4612 [3:20:27<00:06,  1.60s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4609/4612 [3:20:28<00:04,  1.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4610/4612 [3:20:30<00:03,  1.63s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|████████████████▉| 4611/4612 [3:20:32<00:01,  1.71s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Processing Batches: 100%|█████████████████| 4612/4612 [3:20:34<00:00,  2.61s/it]

Error during sentiment analysis: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [ ]:
# Add the sentiments back to the DataFrame if needed
sample_df['sentiment'] = sentiments

# Print the first few results for verification
print(sample_df.head())

In [29]:
sample_df.head()

,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,place_id,sentiment
1,ChZDSUhNMG9nS0VJQ0FnSUR2NVptekJnEAE,"Rosika did an excellent facial, great neck mas...",22 hours ago,2024-12-23 15:22:09.507031,2024-12-23 15:22:09.507073,5.0,Sujatha Madangopal,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
2,ChdDSUhNMG9nS0VJQ0FnSUR2NGJMZndBRRAB,had a great hair washing and blow dry experien...,2 days ago,2024-12-21 15:22:09.507740,2024-12-23 15:22:09.507785,5.0,080 harshitha sridhar,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
3,ChdDSUhNMG9nS0VJQ0FnSUR2dHN1WG9nRRAB,Excellent face massage by Goweri Thankyou you...,2 days ago,2024-12-21 15:22:09.507917,2024-12-23 15:22:09.507958,5.0,Varun Bala Vk,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
4,ChZDSUhNMG9nS0VJQ0FnSUNLdUtTR1NREAE,Aakash raj - Did very good haircut and shave s...,3 days ago,2024-12-20 15:22:09.508090,2024-12-23 15:22:09.508131,5.0,Rajesh Gopalsamy,23,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
5,ChZDSUhNMG9nS0VJQ0FnSUR2M01DbWR3EAE,Excellent hair spa service by Rosika,4 days ago,2024-12-19 15:22:09.508263,2024-12-23 15:22:09.508304,5.0,Kaviya,19,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive

In [30]:
sample_df.to_csv("data/naturals_sentiments.csv")

In [31]:
len(sample_df)

46522

### Read Data

In [32]:
sentiments_df = pd.read_csv("data/naturals_sentiments.csv")

In [33]:
sentiments_df.head()

,Unnamed: 0,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,place_id,sentiment
0,1,ChZDSUhNMG9nS0VJQ0FnSUR2NVptekJnEAE,"Rosika did an excellent facial, great neck mas...",22 hours ago,2024-12-23 15:22:09.507031,2024-12-23 15:22:09.507073,5.0,Sujatha Madangopal,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
1,2,ChdDSUhNMG9nS0VJQ0FnSUR2NGJMZndBRRAB,had a great hair washing and blow dry experien...,2 days ago,2024-12-21 15:22:09.507740,2024-12-23 15:22:09.507785,5.0,080 harshitha sridhar,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
2,3,ChdDSUhNMG9nS0VJQ0FnSUR2dHN1WG9nRRAB,Excellent face massage by Goweri Thankyou you...,2 days ago,2024-12-21 15:22:09.507917,2024-12-23 15:22:09.507958,5.0,Varun Bala Vk,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
3,4,ChZDSUhNMG9nS0VJQ0FnSUNLdUtTR1NREAE,Aakash raj - Did very good haircut and shave s...,3 days ago,2024-12-20 15:22:09.508090,2024-12-23 15:22:09.508131,5.0,Rajesh Gopalsamy,23,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
4,5,ChZDSUhNMG9nS0VJQ0FnSUR2M01DbWR3EAE,Excellent hair spa service by Rosika,4 days ago,2024-12-19 15:22:09.508263,2024-12-23 15:22:09.508304,5.0,Kaviya,19,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive

In [34]:
sentiments_df["sentiment"].value_counts()

sentiment
Positive                                                                                                       43866
Neutral                                                                                                         1220
Negative                                                                                                        1010
Mixed                                                                                                            294
Neutral (The sentiment is unclear due to missing information)                                                      2
                                                                                                               ...
Neutral (The text "Pramila" is a name and does not express any sentiment)                                          1
Positive (The text "Bk hairstyle super service" expresses a positive sentiment towards a hairstyle service)        1
Neutral (The text "Gowsi" is a name and does not express any sentiment)                                            1
Kavitha service good 👍 - Positive                                                                                  1
Very nice service, thank you so much Mrs. Rajeshwari. - Positive                                                   1
Name: count, Length: 135, dtype: int64

In [35]:
# Get value counts of the 'sentiment' column
value_counts = sentiments_df["sentiment"].value_counts()

sentiments_df[sentiments_df["sentiment"].isin(value_counts[value_counts <= 2].index)]

,Unnamed: 0,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,place_id,sentiment
2375,2942,ChZDSUhNMG9nS0VJQ0FnSUR6aHN2WWV3EAE,I am statifed the hair services,6 months ago,2024-06-23 16:33:29.745855,2024-12-23 16:33:29.745903,5.0,Jee Vithya,0,ChIJ38JlxW1lUjoRVB-uo0b6CZQ,"Positive (Assuming ""statifed"" is a typo for ""s..."
4725,5572,ChdDSUhNMG9nS0VJQ0FnSURQbExDT21nRRAB,Hidrafacial nalla result kedachathu Beulah,3 weeks ago,2024-12-02 18:08:07.655470,2024-12-23 18:08:07.655511,4.0,Roja papitha,0,ChIJX2cOPjxnUjoRehfttXmstSA,Beulah's HydraFacial gave good results. - Posi...
4726,5574,ChZDSUhNMG9nS0VJQ0FnSUNQc2ZiakN3EAE,It's very good work Beulah ♥️,3 weeks ago,2024-12-02 18:08:07.655850,2024-12-23 18:08:07.655893,5.0,Arthipriya R,1,ChIJX2cOPjxnUjoRehfttXmstSA,It's very good work Beulah ♥️ - Positive
4727,5575,ChdDSUhNMG9nS0VJQ0FnSURua192V3VnRRAB,Had a hair cut which was fabulous ....great wo...,2 months ago,2024-10-23 18:08:07.656043,2024-12-23 18:08:07.656129,5.0,Bhoomi Mishra,0,ChIJX2cOPjxnUjoRehfttXmstSA,Had a hair cut which was fabulous ....great wo...
4728,5577,ChdDSUhNMG9nS0VJQ0FnSUNuMF9UanNBRRAB,I had a wonderful Hydra facial at *Naturals Sa...,2 months ago,2024-10-23 18:08:11.797140,2024-12-23 18:08:11.797206,5.0,Anitha Anitha,0,ChIJX2cOPjxnUjoRehfttXmstSA,I had a wonderful Hydra facial at *Naturals Sa...
...,...,...,...,...,...,...,...,...,...,...,...
45065,51539,ChdDSUhNMG9nS0VJQ0FnSUNYMDhMQzJRRRAB,I done facial..So much Satisfied.. Thank you m...,2 months ago,2024-10-24 13:41:58.731547,2024-12-24 13:41:58.731608,5.0,Bhuvanesh Kumar,0,ChIJu08uvNxvUjoRnU8vgmdp4qc,I had a facial. So much satisfaction. Thank yo...
45066,51540,ChZDSUhNMG9nS0VJQ0FnSUNYclktUGV3EAE,Latha this person did really well,2 months ago,2024-10-24 13:41:58.731767,2024-12-24 13:41:58.731820,5.0,Seneka Ravi,0,ChIJu08uvNxvUjoRnU8vgmdp4qc,"Latha, this person did really well. - Positive"
45067,51541,ChdDSUhNMG9nS0VJQ0FnSUNYclpYdm5BRRAB,Latha and Raji Serrvice was very good,2 months ago,2024-10-24 13:41:58.731974,2024-12-24 13:41:58.732026,5.0,Meena RM,0,ChIJu08uvNxvUjoRnU8vgmdp4qc,Latha and Raji's service was very good. - Posi...
45068,51542,ChZDSUhNMG9nS0VJQ0FnSUN4cjhfdGZBEAE,Wonderful service from Rajesh. Please maintain...,2 months ago,2024-10-24 13:41:58.732160,2024-12-24 13:41:58.732210,5.0,Manoj Karan,4,ChIJu08uvNxvUjoRnU8vgmdp4qc,Wonderful service from Rajesh. Please maintain...
45069,51543,ChdDSUhNMG9nS0VJQ0FnSUNYcmFhZWlBRRAB,Very nice service thank you so much Mrs. Rajes...,2 months ago,2024-10-24 13:41:58.732345,2024-12-24 13:41:58.732397,5.0,Raashmica A,0,ChIJu08uvNxvUjoRnU8vgmdp4qc,"Very nice service, thank you so much Mrs. Raje..."